/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import thebluealliance.api.model.DistrictInsightDistrictData;
import thebluealliance.api.model.DistrictInsightTeamDataValue;

/**
 * DistrictInsight
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class DistrictInsight {
  public static final String SERIALIZED_NAME_DISTRICT_DATA = "district_data";
  @SerializedName(SERIALIZED_NAME_DISTRICT_DATA)
  @javax.annotation.Nullable
  private DistrictInsightDistrictData districtData;

  public static final String SERIALIZED_NAME_TEAM_DATA = "team_data";
  @SerializedName(SERIALIZED_NAME_TEAM_DATA)
  @javax.annotation.Nullable
  private Map<String, DistrictInsightTeamDataValue> teamData;

  public DistrictInsight() {
  }

  public DistrictInsight districtData(@javax.annotation.Nullable DistrictInsightDistrictData districtData) {
    
    this.districtData = districtData;
    return this;
  }

  /**
   * Get districtData
   * @return districtData
   */
  @javax.annotation.Nullable

  public DistrictInsightDistrictData getDistrictData() {
    return districtData;
  }


  public void setDistrictData(@javax.annotation.Nullable DistrictInsightDistrictData districtData) {
    this.districtData = districtData;
  }

  public DistrictInsight teamData(@javax.annotation.Nullable Map<String, DistrictInsightTeamDataValue> teamData) {
    
    this.teamData = teamData;
    return this;
  }

  public DistrictInsight putTeamDataItem(String key, DistrictInsightTeamDataValue teamDataItem) {
    this.teamData.put(key, teamDataItem);
    return this;
  }

  /**
   * Get teamData
   * @return teamData
   */
  @javax.annotation.Nullable

  public Map<String, DistrictInsightTeamDataValue> getTeamData() {
    return teamData;
  }


  public void setTeamData(@javax.annotation.Nullable Map<String, DistrictInsightTeamDataValue> teamData) {
    this.teamData = teamData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistrictInsight districtInsight = (DistrictInsight) o;
    return Objects.equals(this.districtData, districtInsight.districtData) &&
        Objects.equals(this.teamData, districtInsight.teamData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(districtData, teamData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistrictInsight {\n");
    sb.append("    districtData: ").append(toIndentedString(districtData)).append("\n");
    sb.append("    teamData: ").append(toIndentedString(teamData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

