/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * DistrictRankingEventPointsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class DistrictRankingEventPointsInner {
  public static final String SERIALIZED_NAME_DISTRICT_CMP = "district_cmp";
  @SerializedName(SERIALIZED_NAME_DISTRICT_CMP)
  @javax.annotation.Nonnull
  private Boolean districtCmp;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nonnull
  private Integer total;

  public static final String SERIALIZED_NAME_ALLIANCE_POINTS = "alliance_points";
  @SerializedName(SERIALIZED_NAME_ALLIANCE_POINTS)
  @javax.annotation.Nonnull
  private Integer alliancePoints;

  public static final String SERIALIZED_NAME_ELIM_POINTS = "elim_points";
  @SerializedName(SERIALIZED_NAME_ELIM_POINTS)
  @javax.annotation.Nonnull
  private Integer elimPoints;

  public static final String SERIALIZED_NAME_AWARD_POINTS = "award_points";
  @SerializedName(SERIALIZED_NAME_AWARD_POINTS)
  @javax.annotation.Nonnull
  private Integer awardPoints;

  public static final String SERIALIZED_NAME_EVENT_KEY = "event_key";
  @SerializedName(SERIALIZED_NAME_EVENT_KEY)
  @javax.annotation.Nonnull
  private String eventKey;

  public static final String SERIALIZED_NAME_QUAL_POINTS = "qual_points";
  @SerializedName(SERIALIZED_NAME_QUAL_POINTS)
  @javax.annotation.Nonnull
  private Integer qualPoints;

  public DistrictRankingEventPointsInner() {
  }

  public DistrictRankingEventPointsInner districtCmp(@javax.annotation.Nonnull Boolean districtCmp) {
    
    this.districtCmp = districtCmp;
    return this;
  }

  /**
   * &#x60;true&#x60; if this event is a District Championship event.
   * @return districtCmp
   */
  @javax.annotation.Nonnull

  public Boolean getDistrictCmp() {
    return districtCmp;
  }


  public void setDistrictCmp(@javax.annotation.Nonnull Boolean districtCmp) {
    this.districtCmp = districtCmp;
  }

  public DistrictRankingEventPointsInner total(@javax.annotation.Nonnull Integer total) {
    
    this.total = total;
    return this;
  }

  /**
   * Total points awarded at this event.
   * @return total
   */
  @javax.annotation.Nonnull

  public Integer getTotal() {
    return total;
  }


  public void setTotal(@javax.annotation.Nonnull Integer total) {
    this.total = total;
  }

  public DistrictRankingEventPointsInner alliancePoints(@javax.annotation.Nonnull Integer alliancePoints) {
    
    this.alliancePoints = alliancePoints;
    return this;
  }

  /**
   * Points awarded for alliance selection.
   * @return alliancePoints
   */
  @javax.annotation.Nonnull

  public Integer getAlliancePoints() {
    return alliancePoints;
  }


  public void setAlliancePoints(@javax.annotation.Nonnull Integer alliancePoints) {
    this.alliancePoints = alliancePoints;
  }

  public DistrictRankingEventPointsInner elimPoints(@javax.annotation.Nonnull Integer elimPoints) {
    
    this.elimPoints = elimPoints;
    return this;
  }

  /**
   * Points awarded for elimination match performance.
   * @return elimPoints
   */
  @javax.annotation.Nonnull

  public Integer getElimPoints() {
    return elimPoints;
  }


  public void setElimPoints(@javax.annotation.Nonnull Integer elimPoints) {
    this.elimPoints = elimPoints;
  }

  public DistrictRankingEventPointsInner awardPoints(@javax.annotation.Nonnull Integer awardPoints) {
    
    this.awardPoints = awardPoints;
    return this;
  }

  /**
   * Points awarded for event awards.
   * @return awardPoints
   */
  @javax.annotation.Nonnull

  public Integer getAwardPoints() {
    return awardPoints;
  }


  public void setAwardPoints(@javax.annotation.Nonnull Integer awardPoints) {
    this.awardPoints = awardPoints;
  }

  public DistrictRankingEventPointsInner eventKey(@javax.annotation.Nonnull String eventKey) {
    
    this.eventKey = eventKey;
    return this;
  }

  /**
   * TBA Event key for this event.
   * @return eventKey
   */
  @javax.annotation.Nonnull

  public String getEventKey() {
    return eventKey;
  }


  public void setEventKey(@javax.annotation.Nonnull String eventKey) {
    this.eventKey = eventKey;
  }

  public DistrictRankingEventPointsInner qualPoints(@javax.annotation.Nonnull Integer qualPoints) {
    
    this.qualPoints = qualPoints;
    return this;
  }

  /**
   * Points awarded for qualification match performance.
   * @return qualPoints
   */
  @javax.annotation.Nonnull

  public Integer getQualPoints() {
    return qualPoints;
  }


  public void setQualPoints(@javax.annotation.Nonnull Integer qualPoints) {
    this.qualPoints = qualPoints;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistrictRankingEventPointsInner districtRankingEventPointsInner = (DistrictRankingEventPointsInner) o;
    return Objects.equals(this.districtCmp, districtRankingEventPointsInner.districtCmp) &&
        Objects.equals(this.total, districtRankingEventPointsInner.total) &&
        Objects.equals(this.alliancePoints, districtRankingEventPointsInner.alliancePoints) &&
        Objects.equals(this.elimPoints, districtRankingEventPointsInner.elimPoints) &&
        Objects.equals(this.awardPoints, districtRankingEventPointsInner.awardPoints) &&
        Objects.equals(this.eventKey, districtRankingEventPointsInner.eventKey) &&
        Objects.equals(this.qualPoints, districtRankingEventPointsInner.qualPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(districtCmp, total, alliancePoints, elimPoints, awardPoints, eventKey, qualPoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistrictRankingEventPointsInner {\n");
    sb.append("    districtCmp: ").append(toIndentedString(districtCmp)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    alliancePoints: ").append(toIndentedString(alliancePoints)).append("\n");
    sb.append("    elimPoints: ").append(toIndentedString(elimPoints)).append("\n");
    sb.append("    awardPoints: ").append(toIndentedString(awardPoints)).append("\n");
    sb.append("    eventKey: ").append(toIndentedString(eventKey)).append("\n");
    sb.append("    qualPoints: ").append(toIndentedString(qualPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

