/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import thebluealliance.api.model.WLTRecord;

/**
 * DistrictInsightTeamDataValue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class DistrictInsightTeamDataValue {
  public static final String SERIALIZED_NAME_DISTRICT_SEASONS = "district_seasons";
  @SerializedName(SERIALIZED_NAME_DISTRICT_SEASONS)
  @javax.annotation.Nonnull
  private Integer districtSeasons;

  public static final String SERIALIZED_NAME_TOTAL_DISTRICT_POINTS = "total_district_points";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISTRICT_POINTS)
  @javax.annotation.Nonnull
  private Integer totalDistrictPoints;

  public static final String SERIALIZED_NAME_TOTAL_PRE_DCMP_DISTRICT_POINTS = "total_pre_dcmp_district_points";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRE_DCMP_DISTRICT_POINTS)
  @javax.annotation.Nonnull
  private Integer totalPreDcmpDistrictPoints;

  public static final String SERIALIZED_NAME_DISTRICT_EVENT_WINS = "district_event_wins";
  @SerializedName(SERIALIZED_NAME_DISTRICT_EVENT_WINS)
  @javax.annotation.Nonnull
  private Integer districtEventWins;

  public static final String SERIALIZED_NAME_DCMP_WINS = "dcmp_wins";
  @SerializedName(SERIALIZED_NAME_DCMP_WINS)
  @javax.annotation.Nonnull
  private Integer dcmpWins;

  public static final String SERIALIZED_NAME_TEAM_AWARDS = "team_awards";
  @SerializedName(SERIALIZED_NAME_TEAM_AWARDS)
  @javax.annotation.Nonnull
  private Integer teamAwards;

  public static final String SERIALIZED_NAME_INDIVIDUAL_AWARDS = "individual_awards";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_AWARDS)
  @javax.annotation.Nonnull
  private Integer individualAwards;

  public static final String SERIALIZED_NAME_QUALS_RECORD = "quals_record";
  @SerializedName(SERIALIZED_NAME_QUALS_RECORD)
  @javax.annotation.Nonnull
  private WLTRecord qualsRecord;

  public static final String SERIALIZED_NAME_ELIMS_RECORD = "elims_record";
  @SerializedName(SERIALIZED_NAME_ELIMS_RECORD)
  @javax.annotation.Nonnull
  private WLTRecord elimsRecord;

  public DistrictInsightTeamDataValue() {
  }

  public DistrictInsightTeamDataValue districtSeasons(@javax.annotation.Nonnull Integer districtSeasons) {
    
    this.districtSeasons = districtSeasons;
    return this;
  }

  /**
   * Get districtSeasons
   * @return districtSeasons
   */
  @javax.annotation.Nonnull

  public Integer getDistrictSeasons() {
    return districtSeasons;
  }


  public void setDistrictSeasons(@javax.annotation.Nonnull Integer districtSeasons) {
    this.districtSeasons = districtSeasons;
  }

  public DistrictInsightTeamDataValue totalDistrictPoints(@javax.annotation.Nonnull Integer totalDistrictPoints) {
    
    this.totalDistrictPoints = totalDistrictPoints;
    return this;
  }

  /**
   * Get totalDistrictPoints
   * @return totalDistrictPoints
   */
  @javax.annotation.Nonnull

  public Integer getTotalDistrictPoints() {
    return totalDistrictPoints;
  }


  public void setTotalDistrictPoints(@javax.annotation.Nonnull Integer totalDistrictPoints) {
    this.totalDistrictPoints = totalDistrictPoints;
  }

  public DistrictInsightTeamDataValue totalPreDcmpDistrictPoints(@javax.annotation.Nonnull Integer totalPreDcmpDistrictPoints) {
    
    this.totalPreDcmpDistrictPoints = totalPreDcmpDistrictPoints;
    return this;
  }

  /**
   * Get totalPreDcmpDistrictPoints
   * @return totalPreDcmpDistrictPoints
   */
  @javax.annotation.Nonnull

  public Integer getTotalPreDcmpDistrictPoints() {
    return totalPreDcmpDistrictPoints;
  }


  public void setTotalPreDcmpDistrictPoints(@javax.annotation.Nonnull Integer totalPreDcmpDistrictPoints) {
    this.totalPreDcmpDistrictPoints = totalPreDcmpDistrictPoints;
  }

  public DistrictInsightTeamDataValue districtEventWins(@javax.annotation.Nonnull Integer districtEventWins) {
    
    this.districtEventWins = districtEventWins;
    return this;
  }

  /**
   * Get districtEventWins
   * @return districtEventWins
   */
  @javax.annotation.Nonnull

  public Integer getDistrictEventWins() {
    return districtEventWins;
  }


  public void setDistrictEventWins(@javax.annotation.Nonnull Integer districtEventWins) {
    this.districtEventWins = districtEventWins;
  }

  public DistrictInsightTeamDataValue dcmpWins(@javax.annotation.Nonnull Integer dcmpWins) {
    
    this.dcmpWins = dcmpWins;
    return this;
  }

  /**
   * Get dcmpWins
   * @return dcmpWins
   */
  @javax.annotation.Nonnull

  public Integer getDcmpWins() {
    return dcmpWins;
  }


  public void setDcmpWins(@javax.annotation.Nonnull Integer dcmpWins) {
    this.dcmpWins = dcmpWins;
  }

  public DistrictInsightTeamDataValue teamAwards(@javax.annotation.Nonnull Integer teamAwards) {
    
    this.teamAwards = teamAwards;
    return this;
  }

  /**
   * Get teamAwards
   * @return teamAwards
   */
  @javax.annotation.Nonnull

  public Integer getTeamAwards() {
    return teamAwards;
  }


  public void setTeamAwards(@javax.annotation.Nonnull Integer teamAwards) {
    this.teamAwards = teamAwards;
  }

  public DistrictInsightTeamDataValue individualAwards(@javax.annotation.Nonnull Integer individualAwards) {
    
    this.individualAwards = individualAwards;
    return this;
  }

  /**
   * Get individualAwards
   * @return individualAwards
   */
  @javax.annotation.Nonnull

  public Integer getIndividualAwards() {
    return individualAwards;
  }


  public void setIndividualAwards(@javax.annotation.Nonnull Integer individualAwards) {
    this.individualAwards = individualAwards;
  }

  public DistrictInsightTeamDataValue qualsRecord(@javax.annotation.Nonnull WLTRecord qualsRecord) {
    
    this.qualsRecord = qualsRecord;
    return this;
  }

  /**
   * Get qualsRecord
   * @return qualsRecord
   */
  @javax.annotation.Nonnull

  public WLTRecord getQualsRecord() {
    return qualsRecord;
  }


  public void setQualsRecord(@javax.annotation.Nonnull WLTRecord qualsRecord) {
    this.qualsRecord = qualsRecord;
  }

  public DistrictInsightTeamDataValue elimsRecord(@javax.annotation.Nonnull WLTRecord elimsRecord) {
    
    this.elimsRecord = elimsRecord;
    return this;
  }

  /**
   * Get elimsRecord
   * @return elimsRecord
   */
  @javax.annotation.Nonnull

  public WLTRecord getElimsRecord() {
    return elimsRecord;
  }


  public void setElimsRecord(@javax.annotation.Nonnull WLTRecord elimsRecord) {
    this.elimsRecord = elimsRecord;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistrictInsightTeamDataValue districtInsightTeamDataValue = (DistrictInsightTeamDataValue) o;
    return Objects.equals(this.districtSeasons, districtInsightTeamDataValue.districtSeasons) &&
        Objects.equals(this.totalDistrictPoints, districtInsightTeamDataValue.totalDistrictPoints) &&
        Objects.equals(this.totalPreDcmpDistrictPoints, districtInsightTeamDataValue.totalPreDcmpDistrictPoints) &&
        Objects.equals(this.districtEventWins, districtInsightTeamDataValue.districtEventWins) &&
        Objects.equals(this.dcmpWins, districtInsightTeamDataValue.dcmpWins) &&
        Objects.equals(this.teamAwards, districtInsightTeamDataValue.teamAwards) &&
        Objects.equals(this.individualAwards, districtInsightTeamDataValue.individualAwards) &&
        Objects.equals(this.qualsRecord, districtInsightTeamDataValue.qualsRecord) &&
        Objects.equals(this.elimsRecord, districtInsightTeamDataValue.elimsRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(districtSeasons, totalDistrictPoints, totalPreDcmpDistrictPoints, districtEventWins, dcmpWins, teamAwards, individualAwards, qualsRecord, elimsRecord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistrictInsightTeamDataValue {\n");
    sb.append("    districtSeasons: ").append(toIndentedString(districtSeasons)).append("\n");
    sb.append("    totalDistrictPoints: ").append(toIndentedString(totalDistrictPoints)).append("\n");
    sb.append("    totalPreDcmpDistrictPoints: ").append(toIndentedString(totalPreDcmpDistrictPoints)).append("\n");
    sb.append("    districtEventWins: ").append(toIndentedString(districtEventWins)).append("\n");
    sb.append("    dcmpWins: ").append(toIndentedString(dcmpWins)).append("\n");
    sb.append("    teamAwards: ").append(toIndentedString(teamAwards)).append("\n");
    sb.append("    individualAwards: ").append(toIndentedString(individualAwards)).append("\n");
    sb.append("    qualsRecord: ").append(toIndentedString(qualsRecord)).append("\n");
    sb.append("    elimsRecord: ").append(toIndentedString(elimsRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

