/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * OPR, DPR, and CCWM for teams at the event.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class EventOPRs {
  public static final String SERIALIZED_NAME_OPRS = "oprs";
  @SerializedName(SERIALIZED_NAME_OPRS)
  @javax.annotation.Nullable
  private Map<String, Float> oprs = new HashMap<>();

  public static final String SERIALIZED_NAME_DPRS = "dprs";
  @SerializedName(SERIALIZED_NAME_DPRS)
  @javax.annotation.Nullable
  private Map<String, Float> dprs = new HashMap<>();

  public static final String SERIALIZED_NAME_CCWMS = "ccwms";
  @SerializedName(SERIALIZED_NAME_CCWMS)
  @javax.annotation.Nullable
  private Map<String, Float> ccwms = new HashMap<>();

  public EventOPRs() {
  }

  public EventOPRs oprs(@javax.annotation.Nullable Map<String, Float> oprs) {
    
    this.oprs = oprs;
    return this;
  }

  public EventOPRs putOprsItem(String key, Float oprsItem) {
    if (this.oprs == null) {
      this.oprs = new HashMap<>();
    }
    this.oprs.put(key, oprsItem);
    return this;
  }

  /**
   * A key-value pair with team key (eg &#x60;frc254&#x60;) as key and OPR as value.
   * @return oprs
   */
  @javax.annotation.Nullable

  public Map<String, Float> getOprs() {
    return oprs;
  }


  public void setOprs(@javax.annotation.Nullable Map<String, Float> oprs) {
    this.oprs = oprs;
  }

  public EventOPRs dprs(@javax.annotation.Nullable Map<String, Float> dprs) {
    
    this.dprs = dprs;
    return this;
  }

  public EventOPRs putDprsItem(String key, Float dprsItem) {
    if (this.dprs == null) {
      this.dprs = new HashMap<>();
    }
    this.dprs.put(key, dprsItem);
    return this;
  }

  /**
   * A key-value pair with team key (eg &#x60;frc254&#x60;) as key and DPR as value.
   * @return dprs
   */
  @javax.annotation.Nullable

  public Map<String, Float> getDprs() {
    return dprs;
  }


  public void setDprs(@javax.annotation.Nullable Map<String, Float> dprs) {
    this.dprs = dprs;
  }

  public EventOPRs ccwms(@javax.annotation.Nullable Map<String, Float> ccwms) {
    
    this.ccwms = ccwms;
    return this;
  }

  public EventOPRs putCcwmsItem(String key, Float ccwmsItem) {
    if (this.ccwms == null) {
      this.ccwms = new HashMap<>();
    }
    this.ccwms.put(key, ccwmsItem);
    return this;
  }

  /**
   * A key-value pair with team key (eg &#x60;frc254&#x60;) as key and CCWM as value.
   * @return ccwms
   */
  @javax.annotation.Nullable

  public Map<String, Float> getCcwms() {
    return ccwms;
  }


  public void setCcwms(@javax.annotation.Nullable Map<String, Float> ccwms) {
    this.ccwms = ccwms;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventOPRs eventOPRs = (EventOPRs) o;
    return Objects.equals(this.oprs, eventOPRs.oprs) &&
        Objects.equals(this.dprs, eventOPRs.dprs) &&
        Objects.equals(this.ccwms, eventOPRs.ccwms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oprs, dprs, ccwms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventOPRs {\n");
    sb.append("    oprs: ").append(toIndentedString(oprs)).append("\n");
    sb.append("    dprs: ").append(toIndentedString(dprs)).append("\n");
    sb.append("    ccwms: ").append(toIndentedString(ccwms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

