/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * MatchScoreBreakdown2024Alliance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-12T10:04:04.013721-06:00[America/Chicago]", comments = "Generator version: 7.10.0")
public class MatchScoreBreakdown2024Alliance {
  public static final String SERIALIZED_NAME_ADJUST_POINTS = "adjustPoints";
  @SerializedName(SERIALIZED_NAME_ADJUST_POINTS)
  @javax.annotation.Nullable
  private Integer adjustPoints;

  public static final String SERIALIZED_NAME_AUTO_AMP_NOTE_COUNT = "autoAmpNoteCount";
  @SerializedName(SERIALIZED_NAME_AUTO_AMP_NOTE_COUNT)
  @javax.annotation.Nullable
  private Integer autoAmpNoteCount;

  public static final String SERIALIZED_NAME_AUTO_AMP_NOTE_POINTS = "autoAmpNotePoints";
  @SerializedName(SERIALIZED_NAME_AUTO_AMP_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer autoAmpNotePoints;

  public static final String SERIALIZED_NAME_AUTO_LEAVE_POINTS = "autoLeavePoints";
  @SerializedName(SERIALIZED_NAME_AUTO_LEAVE_POINTS)
  @javax.annotation.Nullable
  private Integer autoLeavePoints;

  public static final String SERIALIZED_NAME_AUTO_LINE_ROBOT1 = "autoLineRobot1";
  @SerializedName(SERIALIZED_NAME_AUTO_LINE_ROBOT1)
  @javax.annotation.Nullable
  private String autoLineRobot1;

  public static final String SERIALIZED_NAME_AUTO_LINE_ROBOT2 = "autoLineRobot2";
  @SerializedName(SERIALIZED_NAME_AUTO_LINE_ROBOT2)
  @javax.annotation.Nullable
  private String autoLineRobot2;

  public static final String SERIALIZED_NAME_AUTO_LINE_ROBOT3 = "autoLineRobot3";
  @SerializedName(SERIALIZED_NAME_AUTO_LINE_ROBOT3)
  @javax.annotation.Nullable
  private String autoLineRobot3;

  public static final String SERIALIZED_NAME_AUTO_POINTS = "autoPoints";
  @SerializedName(SERIALIZED_NAME_AUTO_POINTS)
  @javax.annotation.Nullable
  private Integer autoPoints;

  public static final String SERIALIZED_NAME_AUTO_SPEAKER_NOTE_COUNT = "autoSpeakerNoteCount";
  @SerializedName(SERIALIZED_NAME_AUTO_SPEAKER_NOTE_COUNT)
  @javax.annotation.Nullable
  private Integer autoSpeakerNoteCount;

  public static final String SERIALIZED_NAME_AUTO_SPEAKER_NOTE_POINTS = "autoSpeakerNotePoints";
  @SerializedName(SERIALIZED_NAME_AUTO_SPEAKER_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer autoSpeakerNotePoints;

  public static final String SERIALIZED_NAME_AUTO_TOTAL_NOTE_POINTS = "autoTotalNotePoints";
  @SerializedName(SERIALIZED_NAME_AUTO_TOTAL_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer autoTotalNotePoints;

  public static final String SERIALIZED_NAME_COOP_NOTE_PLAYED = "coopNotePlayed";
  @SerializedName(SERIALIZED_NAME_COOP_NOTE_PLAYED)
  @javax.annotation.Nullable
  private Boolean coopNotePlayed;

  public static final String SERIALIZED_NAME_COOPERTITION_BONUS_ACHIEVED = "coopertitionBonusAchieved";
  @SerializedName(SERIALIZED_NAME_COOPERTITION_BONUS_ACHIEVED)
  @javax.annotation.Nullable
  private Boolean coopertitionBonusAchieved;

  public static final String SERIALIZED_NAME_COOPERTITION_CRITERIA_MET = "coopertitionCriteriaMet";
  @SerializedName(SERIALIZED_NAME_COOPERTITION_CRITERIA_MET)
  @javax.annotation.Nullable
  private Boolean coopertitionCriteriaMet;

  public static final String SERIALIZED_NAME_END_GAME_HARMONY_POINTS = "endGameHarmonyPoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_HARMONY_POINTS)
  @javax.annotation.Nullable
  private Integer endGameHarmonyPoints;

  public static final String SERIALIZED_NAME_END_GAME_NOTE_IN_TRAP_POINTS = "endGameNoteInTrapPoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_NOTE_IN_TRAP_POINTS)
  @javax.annotation.Nullable
  private Integer endGameNoteInTrapPoints;

  public static final String SERIALIZED_NAME_END_GAME_ON_STAGE_POINTS = "endGameOnStagePoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_ON_STAGE_POINTS)
  @javax.annotation.Nullable
  private Integer endGameOnStagePoints;

  public static final String SERIALIZED_NAME_END_GAME_PARK_POINTS = "endGameParkPoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_PARK_POINTS)
  @javax.annotation.Nullable
  private Integer endGameParkPoints;

  public static final String SERIALIZED_NAME_END_GAME_ROBOT1 = "endGameRobot1";
  @SerializedName(SERIALIZED_NAME_END_GAME_ROBOT1)
  @javax.annotation.Nullable
  private String endGameRobot1;

  public static final String SERIALIZED_NAME_END_GAME_ROBOT2 = "endGameRobot2";
  @SerializedName(SERIALIZED_NAME_END_GAME_ROBOT2)
  @javax.annotation.Nullable
  private String endGameRobot2;

  public static final String SERIALIZED_NAME_END_GAME_ROBOT3 = "endGameRobot3";
  @SerializedName(SERIALIZED_NAME_END_GAME_ROBOT3)
  @javax.annotation.Nullable
  private String endGameRobot3;

  public static final String SERIALIZED_NAME_END_GAME_SPOT_LIGHT_BONUS_POINTS = "endGameSpotLightBonusPoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_SPOT_LIGHT_BONUS_POINTS)
  @javax.annotation.Nullable
  private Integer endGameSpotLightBonusPoints;

  public static final String SERIALIZED_NAME_END_GAME_TOTAL_STAGE_POINTS = "endGameTotalStagePoints";
  @SerializedName(SERIALIZED_NAME_END_GAME_TOTAL_STAGE_POINTS)
  @javax.annotation.Nullable
  private Integer endGameTotalStagePoints;

  public static final String SERIALIZED_NAME_ENSEMBLE_BONUS_ACHIEVED = "ensembleBonusAchieved";
  @SerializedName(SERIALIZED_NAME_ENSEMBLE_BONUS_ACHIEVED)
  @javax.annotation.Nullable
  private Boolean ensembleBonusAchieved;

  public static final String SERIALIZED_NAME_ENSEMBLE_BONUS_ON_STAGE_ROBOTS_THRESHOLD = "ensembleBonusOnStageRobotsThreshold";
  @SerializedName(SERIALIZED_NAME_ENSEMBLE_BONUS_ON_STAGE_ROBOTS_THRESHOLD)
  @javax.annotation.Nullable
  private Integer ensembleBonusOnStageRobotsThreshold;

  public static final String SERIALIZED_NAME_ENSEMBLE_BONUS_STAGE_POINTS_THRESHOLD = "ensembleBonusStagePointsThreshold";
  @SerializedName(SERIALIZED_NAME_ENSEMBLE_BONUS_STAGE_POINTS_THRESHOLD)
  @javax.annotation.Nullable
  private Integer ensembleBonusStagePointsThreshold;

  public static final String SERIALIZED_NAME_FOUL_COUNT = "foulCount";
  @SerializedName(SERIALIZED_NAME_FOUL_COUNT)
  @javax.annotation.Nullable
  private Integer foulCount;

  public static final String SERIALIZED_NAME_FOUL_POINTS = "foulPoints";
  @SerializedName(SERIALIZED_NAME_FOUL_POINTS)
  @javax.annotation.Nullable
  private Integer foulPoints;

  public static final String SERIALIZED_NAME_G206_PENALTY = "g206Penalty";
  @SerializedName(SERIALIZED_NAME_G206_PENALTY)
  @javax.annotation.Nullable
  private Boolean g206Penalty;

  public static final String SERIALIZED_NAME_G408_PENALTY = "g408Penalty";
  @SerializedName(SERIALIZED_NAME_G408_PENALTY)
  @javax.annotation.Nullable
  private Boolean g408Penalty;

  public static final String SERIALIZED_NAME_G424_PENALTY = "g424Penalty";
  @SerializedName(SERIALIZED_NAME_G424_PENALTY)
  @javax.annotation.Nullable
  private Boolean g424Penalty;

  public static final String SERIALIZED_NAME_MELODY_BONUS_ACHIEVED = "melodyBonusAchieved";
  @SerializedName(SERIALIZED_NAME_MELODY_BONUS_ACHIEVED)
  @javax.annotation.Nullable
  private Boolean melodyBonusAchieved;

  public static final String SERIALIZED_NAME_MELODY_BONUS_THRESHOLD = "melodyBonusThreshold";
  @SerializedName(SERIALIZED_NAME_MELODY_BONUS_THRESHOLD)
  @javax.annotation.Nullable
  private Integer melodyBonusThreshold;

  public static final String SERIALIZED_NAME_MELODY_BONUS_THRESHOLD_COOP = "melodyBonusThresholdCoop";
  @SerializedName(SERIALIZED_NAME_MELODY_BONUS_THRESHOLD_COOP)
  @javax.annotation.Nullable
  private Integer melodyBonusThresholdCoop;

  public static final String SERIALIZED_NAME_MELODY_BONUS_THRESHOLD_NON_COOP = "melodyBonusThresholdNonCoop";
  @SerializedName(SERIALIZED_NAME_MELODY_BONUS_THRESHOLD_NON_COOP)
  @javax.annotation.Nullable
  private Integer melodyBonusThresholdNonCoop;

  public static final String SERIALIZED_NAME_MIC_CENTER_STAGE = "micCenterStage";
  @SerializedName(SERIALIZED_NAME_MIC_CENTER_STAGE)
  @javax.annotation.Nullable
  private Boolean micCenterStage;

  public static final String SERIALIZED_NAME_MIC_STAGE_LEFT = "micStageLeft";
  @SerializedName(SERIALIZED_NAME_MIC_STAGE_LEFT)
  @javax.annotation.Nullable
  private Boolean micStageLeft;

  public static final String SERIALIZED_NAME_MIC_STAGE_RIGHT = "micStageRight";
  @SerializedName(SERIALIZED_NAME_MIC_STAGE_RIGHT)
  @javax.annotation.Nullable
  private Boolean micStageRight;

  public static final String SERIALIZED_NAME_RP = "rp";
  @SerializedName(SERIALIZED_NAME_RP)
  @javax.annotation.Nullable
  private Integer rp;

  public static final String SERIALIZED_NAME_TECH_FOUL_COUNT = "techFoulCount";
  @SerializedName(SERIALIZED_NAME_TECH_FOUL_COUNT)
  @javax.annotation.Nullable
  private Integer techFoulCount;

  public static final String SERIALIZED_NAME_TELEOP_AMP_NOTE_COUNT = "teleopAmpNoteCount";
  @SerializedName(SERIALIZED_NAME_TELEOP_AMP_NOTE_COUNT)
  @javax.annotation.Nullable
  private Integer teleopAmpNoteCount;

  public static final String SERIALIZED_NAME_TELEOP_AMP_NOTE_POINTS = "teleopAmpNotePoints";
  @SerializedName(SERIALIZED_NAME_TELEOP_AMP_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer teleopAmpNotePoints;

  public static final String SERIALIZED_NAME_TELEOP_POINTS = "teleopPoints";
  @SerializedName(SERIALIZED_NAME_TELEOP_POINTS)
  @javax.annotation.Nullable
  private Integer teleopPoints;

  public static final String SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_AMPLIFIED_COUNT = "teleopSpeakerNoteAmplifiedCount";
  @SerializedName(SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_AMPLIFIED_COUNT)
  @javax.annotation.Nullable
  private Integer teleopSpeakerNoteAmplifiedCount;

  public static final String SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_AMPLIFIED_POINTS = "teleopSpeakerNoteAmplifiedPoints";
  @SerializedName(SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_AMPLIFIED_POINTS)
  @javax.annotation.Nullable
  private Integer teleopSpeakerNoteAmplifiedPoints;

  public static final String SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_COUNT = "teleopSpeakerNoteCount";
  @SerializedName(SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_COUNT)
  @javax.annotation.Nullable
  private Integer teleopSpeakerNoteCount;

  public static final String SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_POINTS = "teleopSpeakerNotePoints";
  @SerializedName(SERIALIZED_NAME_TELEOP_SPEAKER_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer teleopSpeakerNotePoints;

  public static final String SERIALIZED_NAME_TELEOP_TOTAL_NOTE_POINTS = "teleopTotalNotePoints";
  @SerializedName(SERIALIZED_NAME_TELEOP_TOTAL_NOTE_POINTS)
  @javax.annotation.Nullable
  private Integer teleopTotalNotePoints;

  public static final String SERIALIZED_NAME_TOTAL_POINTS = "totalPoints";
  @SerializedName(SERIALIZED_NAME_TOTAL_POINTS)
  @javax.annotation.Nullable
  private Integer totalPoints;

  public static final String SERIALIZED_NAME_TRAP_CENTER_STAGE = "trapCenterStage";
  @SerializedName(SERIALIZED_NAME_TRAP_CENTER_STAGE)
  @javax.annotation.Nullable
  private Boolean trapCenterStage;

  public static final String SERIALIZED_NAME_TRAP_STAGE_LEFT = "trapStageLeft";
  @SerializedName(SERIALIZED_NAME_TRAP_STAGE_LEFT)
  @javax.annotation.Nullable
  private Boolean trapStageLeft;

  public static final String SERIALIZED_NAME_TRAP_STAGE_RIGHT = "trapStageRight";
  @SerializedName(SERIALIZED_NAME_TRAP_STAGE_RIGHT)
  @javax.annotation.Nullable
  private Boolean trapStageRight;

  public MatchScoreBreakdown2024Alliance() {
  }

  public MatchScoreBreakdown2024Alliance adjustPoints(@javax.annotation.Nullable Integer adjustPoints) {
    
    this.adjustPoints = adjustPoints;
    return this;
  }

  /**
   * Get adjustPoints
   * @return adjustPoints
   */
  @javax.annotation.Nullable

  public Integer getAdjustPoints() {
    return adjustPoints;
  }


  public void setAdjustPoints(@javax.annotation.Nullable Integer adjustPoints) {
    this.adjustPoints = adjustPoints;
  }

  public MatchScoreBreakdown2024Alliance autoAmpNoteCount(@javax.annotation.Nullable Integer autoAmpNoteCount) {
    
    this.autoAmpNoteCount = autoAmpNoteCount;
    return this;
  }

  /**
   * Get autoAmpNoteCount
   * @return autoAmpNoteCount
   */
  @javax.annotation.Nullable

  public Integer getAutoAmpNoteCount() {
    return autoAmpNoteCount;
  }


  public void setAutoAmpNoteCount(@javax.annotation.Nullable Integer autoAmpNoteCount) {
    this.autoAmpNoteCount = autoAmpNoteCount;
  }

  public MatchScoreBreakdown2024Alliance autoAmpNotePoints(@javax.annotation.Nullable Integer autoAmpNotePoints) {
    
    this.autoAmpNotePoints = autoAmpNotePoints;
    return this;
  }

  /**
   * Get autoAmpNotePoints
   * @return autoAmpNotePoints
   */
  @javax.annotation.Nullable

  public Integer getAutoAmpNotePoints() {
    return autoAmpNotePoints;
  }


  public void setAutoAmpNotePoints(@javax.annotation.Nullable Integer autoAmpNotePoints) {
    this.autoAmpNotePoints = autoAmpNotePoints;
  }

  public MatchScoreBreakdown2024Alliance autoLeavePoints(@javax.annotation.Nullable Integer autoLeavePoints) {
    
    this.autoLeavePoints = autoLeavePoints;
    return this;
  }

  /**
   * Get autoLeavePoints
   * @return autoLeavePoints
   */
  @javax.annotation.Nullable

  public Integer getAutoLeavePoints() {
    return autoLeavePoints;
  }


  public void setAutoLeavePoints(@javax.annotation.Nullable Integer autoLeavePoints) {
    this.autoLeavePoints = autoLeavePoints;
  }

  public MatchScoreBreakdown2024Alliance autoLineRobot1(@javax.annotation.Nullable String autoLineRobot1) {
    
    this.autoLineRobot1 = autoLineRobot1;
    return this;
  }

  /**
   * Get autoLineRobot1
   * @return autoLineRobot1
   */
  @javax.annotation.Nullable

  public String getAutoLineRobot1() {
    return autoLineRobot1;
  }


  public void setAutoLineRobot1(@javax.annotation.Nullable String autoLineRobot1) {
    this.autoLineRobot1 = autoLineRobot1;
  }

  public MatchScoreBreakdown2024Alliance autoLineRobot2(@javax.annotation.Nullable String autoLineRobot2) {
    
    this.autoLineRobot2 = autoLineRobot2;
    return this;
  }

  /**
   * Get autoLineRobot2
   * @return autoLineRobot2
   */
  @javax.annotation.Nullable

  public String getAutoLineRobot2() {
    return autoLineRobot2;
  }


  public void setAutoLineRobot2(@javax.annotation.Nullable String autoLineRobot2) {
    this.autoLineRobot2 = autoLineRobot2;
  }

  public MatchScoreBreakdown2024Alliance autoLineRobot3(@javax.annotation.Nullable String autoLineRobot3) {
    
    this.autoLineRobot3 = autoLineRobot3;
    return this;
  }

  /**
   * Get autoLineRobot3
   * @return autoLineRobot3
   */
  @javax.annotation.Nullable

  public String getAutoLineRobot3() {
    return autoLineRobot3;
  }


  public void setAutoLineRobot3(@javax.annotation.Nullable String autoLineRobot3) {
    this.autoLineRobot3 = autoLineRobot3;
  }

  public MatchScoreBreakdown2024Alliance autoPoints(@javax.annotation.Nullable Integer autoPoints) {
    
    this.autoPoints = autoPoints;
    return this;
  }

  /**
   * Get autoPoints
   * @return autoPoints
   */
  @javax.annotation.Nullable

  public Integer getAutoPoints() {
    return autoPoints;
  }


  public void setAutoPoints(@javax.annotation.Nullable Integer autoPoints) {
    this.autoPoints = autoPoints;
  }

  public MatchScoreBreakdown2024Alliance autoSpeakerNoteCount(@javax.annotation.Nullable Integer autoSpeakerNoteCount) {
    
    this.autoSpeakerNoteCount = autoSpeakerNoteCount;
    return this;
  }

  /**
   * Get autoSpeakerNoteCount
   * @return autoSpeakerNoteCount
   */
  @javax.annotation.Nullable

  public Integer getAutoSpeakerNoteCount() {
    return autoSpeakerNoteCount;
  }


  public void setAutoSpeakerNoteCount(@javax.annotation.Nullable Integer autoSpeakerNoteCount) {
    this.autoSpeakerNoteCount = autoSpeakerNoteCount;
  }

  public MatchScoreBreakdown2024Alliance autoSpeakerNotePoints(@javax.annotation.Nullable Integer autoSpeakerNotePoints) {
    
    this.autoSpeakerNotePoints = autoSpeakerNotePoints;
    return this;
  }

  /**
   * Get autoSpeakerNotePoints
   * @return autoSpeakerNotePoints
   */
  @javax.annotation.Nullable

  public Integer getAutoSpeakerNotePoints() {
    return autoSpeakerNotePoints;
  }


  public void setAutoSpeakerNotePoints(@javax.annotation.Nullable Integer autoSpeakerNotePoints) {
    this.autoSpeakerNotePoints = autoSpeakerNotePoints;
  }

  public MatchScoreBreakdown2024Alliance autoTotalNotePoints(@javax.annotation.Nullable Integer autoTotalNotePoints) {
    
    this.autoTotalNotePoints = autoTotalNotePoints;
    return this;
  }

  /**
   * Get autoTotalNotePoints
   * @return autoTotalNotePoints
   */
  @javax.annotation.Nullable

  public Integer getAutoTotalNotePoints() {
    return autoTotalNotePoints;
  }


  public void setAutoTotalNotePoints(@javax.annotation.Nullable Integer autoTotalNotePoints) {
    this.autoTotalNotePoints = autoTotalNotePoints;
  }

  public MatchScoreBreakdown2024Alliance coopNotePlayed(@javax.annotation.Nullable Boolean coopNotePlayed) {
    
    this.coopNotePlayed = coopNotePlayed;
    return this;
  }

  /**
   * Get coopNotePlayed
   * @return coopNotePlayed
   */
  @javax.annotation.Nullable

  public Boolean getCoopNotePlayed() {
    return coopNotePlayed;
  }


  public void setCoopNotePlayed(@javax.annotation.Nullable Boolean coopNotePlayed) {
    this.coopNotePlayed = coopNotePlayed;
  }

  public MatchScoreBreakdown2024Alliance coopertitionBonusAchieved(@javax.annotation.Nullable Boolean coopertitionBonusAchieved) {
    
    this.coopertitionBonusAchieved = coopertitionBonusAchieved;
    return this;
  }

  /**
   * Get coopertitionBonusAchieved
   * @return coopertitionBonusAchieved
   */
  @javax.annotation.Nullable

  public Boolean getCoopertitionBonusAchieved() {
    return coopertitionBonusAchieved;
  }


  public void setCoopertitionBonusAchieved(@javax.annotation.Nullable Boolean coopertitionBonusAchieved) {
    this.coopertitionBonusAchieved = coopertitionBonusAchieved;
  }

  public MatchScoreBreakdown2024Alliance coopertitionCriteriaMet(@javax.annotation.Nullable Boolean coopertitionCriteriaMet) {
    
    this.coopertitionCriteriaMet = coopertitionCriteriaMet;
    return this;
  }

  /**
   * Get coopertitionCriteriaMet
   * @return coopertitionCriteriaMet
   */
  @javax.annotation.Nullable

  public Boolean getCoopertitionCriteriaMet() {
    return coopertitionCriteriaMet;
  }


  public void setCoopertitionCriteriaMet(@javax.annotation.Nullable Boolean coopertitionCriteriaMet) {
    this.coopertitionCriteriaMet = coopertitionCriteriaMet;
  }

  public MatchScoreBreakdown2024Alliance endGameHarmonyPoints(@javax.annotation.Nullable Integer endGameHarmonyPoints) {
    
    this.endGameHarmonyPoints = endGameHarmonyPoints;
    return this;
  }

  /**
   * Get endGameHarmonyPoints
   * @return endGameHarmonyPoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameHarmonyPoints() {
    return endGameHarmonyPoints;
  }


  public void setEndGameHarmonyPoints(@javax.annotation.Nullable Integer endGameHarmonyPoints) {
    this.endGameHarmonyPoints = endGameHarmonyPoints;
  }

  public MatchScoreBreakdown2024Alliance endGameNoteInTrapPoints(@javax.annotation.Nullable Integer endGameNoteInTrapPoints) {
    
    this.endGameNoteInTrapPoints = endGameNoteInTrapPoints;
    return this;
  }

  /**
   * Get endGameNoteInTrapPoints
   * @return endGameNoteInTrapPoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameNoteInTrapPoints() {
    return endGameNoteInTrapPoints;
  }


  public void setEndGameNoteInTrapPoints(@javax.annotation.Nullable Integer endGameNoteInTrapPoints) {
    this.endGameNoteInTrapPoints = endGameNoteInTrapPoints;
  }

  public MatchScoreBreakdown2024Alliance endGameOnStagePoints(@javax.annotation.Nullable Integer endGameOnStagePoints) {
    
    this.endGameOnStagePoints = endGameOnStagePoints;
    return this;
  }

  /**
   * Get endGameOnStagePoints
   * @return endGameOnStagePoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameOnStagePoints() {
    return endGameOnStagePoints;
  }


  public void setEndGameOnStagePoints(@javax.annotation.Nullable Integer endGameOnStagePoints) {
    this.endGameOnStagePoints = endGameOnStagePoints;
  }

  public MatchScoreBreakdown2024Alliance endGameParkPoints(@javax.annotation.Nullable Integer endGameParkPoints) {
    
    this.endGameParkPoints = endGameParkPoints;
    return this;
  }

  /**
   * Get endGameParkPoints
   * @return endGameParkPoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameParkPoints() {
    return endGameParkPoints;
  }


  public void setEndGameParkPoints(@javax.annotation.Nullable Integer endGameParkPoints) {
    this.endGameParkPoints = endGameParkPoints;
  }

  public MatchScoreBreakdown2024Alliance endGameRobot1(@javax.annotation.Nullable String endGameRobot1) {
    
    this.endGameRobot1 = endGameRobot1;
    return this;
  }

  /**
   * Get endGameRobot1
   * @return endGameRobot1
   */
  @javax.annotation.Nullable

  public String getEndGameRobot1() {
    return endGameRobot1;
  }


  public void setEndGameRobot1(@javax.annotation.Nullable String endGameRobot1) {
    this.endGameRobot1 = endGameRobot1;
  }

  public MatchScoreBreakdown2024Alliance endGameRobot2(@javax.annotation.Nullable String endGameRobot2) {
    
    this.endGameRobot2 = endGameRobot2;
    return this;
  }

  /**
   * Get endGameRobot2
   * @return endGameRobot2
   */
  @javax.annotation.Nullable

  public String getEndGameRobot2() {
    return endGameRobot2;
  }


  public void setEndGameRobot2(@javax.annotation.Nullable String endGameRobot2) {
    this.endGameRobot2 = endGameRobot2;
  }

  public MatchScoreBreakdown2024Alliance endGameRobot3(@javax.annotation.Nullable String endGameRobot3) {
    
    this.endGameRobot3 = endGameRobot3;
    return this;
  }

  /**
   * Get endGameRobot3
   * @return endGameRobot3
   */
  @javax.annotation.Nullable

  public String getEndGameRobot3() {
    return endGameRobot3;
  }


  public void setEndGameRobot3(@javax.annotation.Nullable String endGameRobot3) {
    this.endGameRobot3 = endGameRobot3;
  }

  public MatchScoreBreakdown2024Alliance endGameSpotLightBonusPoints(@javax.annotation.Nullable Integer endGameSpotLightBonusPoints) {
    
    this.endGameSpotLightBonusPoints = endGameSpotLightBonusPoints;
    return this;
  }

  /**
   * Get endGameSpotLightBonusPoints
   * @return endGameSpotLightBonusPoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameSpotLightBonusPoints() {
    return endGameSpotLightBonusPoints;
  }


  public void setEndGameSpotLightBonusPoints(@javax.annotation.Nullable Integer endGameSpotLightBonusPoints) {
    this.endGameSpotLightBonusPoints = endGameSpotLightBonusPoints;
  }

  public MatchScoreBreakdown2024Alliance endGameTotalStagePoints(@javax.annotation.Nullable Integer endGameTotalStagePoints) {
    
    this.endGameTotalStagePoints = endGameTotalStagePoints;
    return this;
  }

  /**
   * Get endGameTotalStagePoints
   * @return endGameTotalStagePoints
   */
  @javax.annotation.Nullable

  public Integer getEndGameTotalStagePoints() {
    return endGameTotalStagePoints;
  }


  public void setEndGameTotalStagePoints(@javax.annotation.Nullable Integer endGameTotalStagePoints) {
    this.endGameTotalStagePoints = endGameTotalStagePoints;
  }

  public MatchScoreBreakdown2024Alliance ensembleBonusAchieved(@javax.annotation.Nullable Boolean ensembleBonusAchieved) {
    
    this.ensembleBonusAchieved = ensembleBonusAchieved;
    return this;
  }

  /**
   * Get ensembleBonusAchieved
   * @return ensembleBonusAchieved
   */
  @javax.annotation.Nullable

  public Boolean getEnsembleBonusAchieved() {
    return ensembleBonusAchieved;
  }


  public void setEnsembleBonusAchieved(@javax.annotation.Nullable Boolean ensembleBonusAchieved) {
    this.ensembleBonusAchieved = ensembleBonusAchieved;
  }

  public MatchScoreBreakdown2024Alliance ensembleBonusOnStageRobotsThreshold(@javax.annotation.Nullable Integer ensembleBonusOnStageRobotsThreshold) {
    
    this.ensembleBonusOnStageRobotsThreshold = ensembleBonusOnStageRobotsThreshold;
    return this;
  }

  /**
   * Get ensembleBonusOnStageRobotsThreshold
   * @return ensembleBonusOnStageRobotsThreshold
   */
  @javax.annotation.Nullable

  public Integer getEnsembleBonusOnStageRobotsThreshold() {
    return ensembleBonusOnStageRobotsThreshold;
  }


  public void setEnsembleBonusOnStageRobotsThreshold(@javax.annotation.Nullable Integer ensembleBonusOnStageRobotsThreshold) {
    this.ensembleBonusOnStageRobotsThreshold = ensembleBonusOnStageRobotsThreshold;
  }

  public MatchScoreBreakdown2024Alliance ensembleBonusStagePointsThreshold(@javax.annotation.Nullable Integer ensembleBonusStagePointsThreshold) {
    
    this.ensembleBonusStagePointsThreshold = ensembleBonusStagePointsThreshold;
    return this;
  }

  /**
   * Get ensembleBonusStagePointsThreshold
   * @return ensembleBonusStagePointsThreshold
   */
  @javax.annotation.Nullable

  public Integer getEnsembleBonusStagePointsThreshold() {
    return ensembleBonusStagePointsThreshold;
  }


  public void setEnsembleBonusStagePointsThreshold(@javax.annotation.Nullable Integer ensembleBonusStagePointsThreshold) {
    this.ensembleBonusStagePointsThreshold = ensembleBonusStagePointsThreshold;
  }

  public MatchScoreBreakdown2024Alliance foulCount(@javax.annotation.Nullable Integer foulCount) {
    
    this.foulCount = foulCount;
    return this;
  }

  /**
   * Get foulCount
   * @return foulCount
   */
  @javax.annotation.Nullable

  public Integer getFoulCount() {
    return foulCount;
  }


  public void setFoulCount(@javax.annotation.Nullable Integer foulCount) {
    this.foulCount = foulCount;
  }

  public MatchScoreBreakdown2024Alliance foulPoints(@javax.annotation.Nullable Integer foulPoints) {
    
    this.foulPoints = foulPoints;
    return this;
  }

  /**
   * Get foulPoints
   * @return foulPoints
   */
  @javax.annotation.Nullable

  public Integer getFoulPoints() {
    return foulPoints;
  }


  public void setFoulPoints(@javax.annotation.Nullable Integer foulPoints) {
    this.foulPoints = foulPoints;
  }

  public MatchScoreBreakdown2024Alliance g206Penalty(@javax.annotation.Nullable Boolean g206Penalty) {
    
    this.g206Penalty = g206Penalty;
    return this;
  }

  /**
   * Get g206Penalty
   * @return g206Penalty
   */
  @javax.annotation.Nullable

  public Boolean getG206Penalty() {
    return g206Penalty;
  }


  public void setG206Penalty(@javax.annotation.Nullable Boolean g206Penalty) {
    this.g206Penalty = g206Penalty;
  }

  public MatchScoreBreakdown2024Alliance g408Penalty(@javax.annotation.Nullable Boolean g408Penalty) {
    
    this.g408Penalty = g408Penalty;
    return this;
  }

  /**
   * Get g408Penalty
   * @return g408Penalty
   */
  @javax.annotation.Nullable

  public Boolean getG408Penalty() {
    return g408Penalty;
  }


  public void setG408Penalty(@javax.annotation.Nullable Boolean g408Penalty) {
    this.g408Penalty = g408Penalty;
  }

  public MatchScoreBreakdown2024Alliance g424Penalty(@javax.annotation.Nullable Boolean g424Penalty) {
    
    this.g424Penalty = g424Penalty;
    return this;
  }

  /**
   * Get g424Penalty
   * @return g424Penalty
   */
  @javax.annotation.Nullable

  public Boolean getG424Penalty() {
    return g424Penalty;
  }


  public void setG424Penalty(@javax.annotation.Nullable Boolean g424Penalty) {
    this.g424Penalty = g424Penalty;
  }

  public MatchScoreBreakdown2024Alliance melodyBonusAchieved(@javax.annotation.Nullable Boolean melodyBonusAchieved) {
    
    this.melodyBonusAchieved = melodyBonusAchieved;
    return this;
  }

  /**
   * Get melodyBonusAchieved
   * @return melodyBonusAchieved
   */
  @javax.annotation.Nullable

  public Boolean getMelodyBonusAchieved() {
    return melodyBonusAchieved;
  }


  public void setMelodyBonusAchieved(@javax.annotation.Nullable Boolean melodyBonusAchieved) {
    this.melodyBonusAchieved = melodyBonusAchieved;
  }

  public MatchScoreBreakdown2024Alliance melodyBonusThreshold(@javax.annotation.Nullable Integer melodyBonusThreshold) {
    
    this.melodyBonusThreshold = melodyBonusThreshold;
    return this;
  }

  /**
   * Get melodyBonusThreshold
   * @return melodyBonusThreshold
   */
  @javax.annotation.Nullable

  public Integer getMelodyBonusThreshold() {
    return melodyBonusThreshold;
  }


  public void setMelodyBonusThreshold(@javax.annotation.Nullable Integer melodyBonusThreshold) {
    this.melodyBonusThreshold = melodyBonusThreshold;
  }

  public MatchScoreBreakdown2024Alliance melodyBonusThresholdCoop(@javax.annotation.Nullable Integer melodyBonusThresholdCoop) {
    
    this.melodyBonusThresholdCoop = melodyBonusThresholdCoop;
    return this;
  }

  /**
   * Get melodyBonusThresholdCoop
   * @return melodyBonusThresholdCoop
   */
  @javax.annotation.Nullable

  public Integer getMelodyBonusThresholdCoop() {
    return melodyBonusThresholdCoop;
  }


  public void setMelodyBonusThresholdCoop(@javax.annotation.Nullable Integer melodyBonusThresholdCoop) {
    this.melodyBonusThresholdCoop = melodyBonusThresholdCoop;
  }

  public MatchScoreBreakdown2024Alliance melodyBonusThresholdNonCoop(@javax.annotation.Nullable Integer melodyBonusThresholdNonCoop) {
    
    this.melodyBonusThresholdNonCoop = melodyBonusThresholdNonCoop;
    return this;
  }

  /**
   * Get melodyBonusThresholdNonCoop
   * @return melodyBonusThresholdNonCoop
   */
  @javax.annotation.Nullable

  public Integer getMelodyBonusThresholdNonCoop() {
    return melodyBonusThresholdNonCoop;
  }


  public void setMelodyBonusThresholdNonCoop(@javax.annotation.Nullable Integer melodyBonusThresholdNonCoop) {
    this.melodyBonusThresholdNonCoop = melodyBonusThresholdNonCoop;
  }

  public MatchScoreBreakdown2024Alliance micCenterStage(@javax.annotation.Nullable Boolean micCenterStage) {
    
    this.micCenterStage = micCenterStage;
    return this;
  }

  /**
   * Get micCenterStage
   * @return micCenterStage
   */
  @javax.annotation.Nullable

  public Boolean getMicCenterStage() {
    return micCenterStage;
  }


  public void setMicCenterStage(@javax.annotation.Nullable Boolean micCenterStage) {
    this.micCenterStage = micCenterStage;
  }

  public MatchScoreBreakdown2024Alliance micStageLeft(@javax.annotation.Nullable Boolean micStageLeft) {
    
    this.micStageLeft = micStageLeft;
    return this;
  }

  /**
   * Get micStageLeft
   * @return micStageLeft
   */
  @javax.annotation.Nullable

  public Boolean getMicStageLeft() {
    return micStageLeft;
  }


  public void setMicStageLeft(@javax.annotation.Nullable Boolean micStageLeft) {
    this.micStageLeft = micStageLeft;
  }

  public MatchScoreBreakdown2024Alliance micStageRight(@javax.annotation.Nullable Boolean micStageRight) {
    
    this.micStageRight = micStageRight;
    return this;
  }

  /**
   * Get micStageRight
   * @return micStageRight
   */
  @javax.annotation.Nullable

  public Boolean getMicStageRight() {
    return micStageRight;
  }


  public void setMicStageRight(@javax.annotation.Nullable Boolean micStageRight) {
    this.micStageRight = micStageRight;
  }

  public MatchScoreBreakdown2024Alliance rp(@javax.annotation.Nullable Integer rp) {
    
    this.rp = rp;
    return this;
  }

  /**
   * Get rp
   * @return rp
   */
  @javax.annotation.Nullable

  public Integer getRp() {
    return rp;
  }


  public void setRp(@javax.annotation.Nullable Integer rp) {
    this.rp = rp;
  }

  public MatchScoreBreakdown2024Alliance techFoulCount(@javax.annotation.Nullable Integer techFoulCount) {
    
    this.techFoulCount = techFoulCount;
    return this;
  }

  /**
   * Get techFoulCount
   * @return techFoulCount
   */
  @javax.annotation.Nullable

  public Integer getTechFoulCount() {
    return techFoulCount;
  }


  public void setTechFoulCount(@javax.annotation.Nullable Integer techFoulCount) {
    this.techFoulCount = techFoulCount;
  }

  public MatchScoreBreakdown2024Alliance teleopAmpNoteCount(@javax.annotation.Nullable Integer teleopAmpNoteCount) {
    
    this.teleopAmpNoteCount = teleopAmpNoteCount;
    return this;
  }

  /**
   * Get teleopAmpNoteCount
   * @return teleopAmpNoteCount
   */
  @javax.annotation.Nullable

  public Integer getTeleopAmpNoteCount() {
    return teleopAmpNoteCount;
  }


  public void setTeleopAmpNoteCount(@javax.annotation.Nullable Integer teleopAmpNoteCount) {
    this.teleopAmpNoteCount = teleopAmpNoteCount;
  }

  public MatchScoreBreakdown2024Alliance teleopAmpNotePoints(@javax.annotation.Nullable Integer teleopAmpNotePoints) {
    
    this.teleopAmpNotePoints = teleopAmpNotePoints;
    return this;
  }

  /**
   * Get teleopAmpNotePoints
   * @return teleopAmpNotePoints
   */
  @javax.annotation.Nullable

  public Integer getTeleopAmpNotePoints() {
    return teleopAmpNotePoints;
  }


  public void setTeleopAmpNotePoints(@javax.annotation.Nullable Integer teleopAmpNotePoints) {
    this.teleopAmpNotePoints = teleopAmpNotePoints;
  }

  public MatchScoreBreakdown2024Alliance teleopPoints(@javax.annotation.Nullable Integer teleopPoints) {
    
    this.teleopPoints = teleopPoints;
    return this;
  }

  /**
   * Get teleopPoints
   * @return teleopPoints
   */
  @javax.annotation.Nullable

  public Integer getTeleopPoints() {
    return teleopPoints;
  }


  public void setTeleopPoints(@javax.annotation.Nullable Integer teleopPoints) {
    this.teleopPoints = teleopPoints;
  }

  public MatchScoreBreakdown2024Alliance teleopSpeakerNoteAmplifiedCount(@javax.annotation.Nullable Integer teleopSpeakerNoteAmplifiedCount) {
    
    this.teleopSpeakerNoteAmplifiedCount = teleopSpeakerNoteAmplifiedCount;
    return this;
  }

  /**
   * Get teleopSpeakerNoteAmplifiedCount
   * @return teleopSpeakerNoteAmplifiedCount
   */
  @javax.annotation.Nullable

  public Integer getTeleopSpeakerNoteAmplifiedCount() {
    return teleopSpeakerNoteAmplifiedCount;
  }


  public void setTeleopSpeakerNoteAmplifiedCount(@javax.annotation.Nullable Integer teleopSpeakerNoteAmplifiedCount) {
    this.teleopSpeakerNoteAmplifiedCount = teleopSpeakerNoteAmplifiedCount;
  }

  public MatchScoreBreakdown2024Alliance teleopSpeakerNoteAmplifiedPoints(@javax.annotation.Nullable Integer teleopSpeakerNoteAmplifiedPoints) {
    
    this.teleopSpeakerNoteAmplifiedPoints = teleopSpeakerNoteAmplifiedPoints;
    return this;
  }

  /**
   * Get teleopSpeakerNoteAmplifiedPoints
   * @return teleopSpeakerNoteAmplifiedPoints
   */
  @javax.annotation.Nullable

  public Integer getTeleopSpeakerNoteAmplifiedPoints() {
    return teleopSpeakerNoteAmplifiedPoints;
  }


  public void setTeleopSpeakerNoteAmplifiedPoints(@javax.annotation.Nullable Integer teleopSpeakerNoteAmplifiedPoints) {
    this.teleopSpeakerNoteAmplifiedPoints = teleopSpeakerNoteAmplifiedPoints;
  }

  public MatchScoreBreakdown2024Alliance teleopSpeakerNoteCount(@javax.annotation.Nullable Integer teleopSpeakerNoteCount) {
    
    this.teleopSpeakerNoteCount = teleopSpeakerNoteCount;
    return this;
  }

  /**
   * Get teleopSpeakerNoteCount
   * @return teleopSpeakerNoteCount
   */
  @javax.annotation.Nullable

  public Integer getTeleopSpeakerNoteCount() {
    return teleopSpeakerNoteCount;
  }


  public void setTeleopSpeakerNoteCount(@javax.annotation.Nullable Integer teleopSpeakerNoteCount) {
    this.teleopSpeakerNoteCount = teleopSpeakerNoteCount;
  }

  public MatchScoreBreakdown2024Alliance teleopSpeakerNotePoints(@javax.annotation.Nullable Integer teleopSpeakerNotePoints) {
    
    this.teleopSpeakerNotePoints = teleopSpeakerNotePoints;
    return this;
  }

  /**
   * Get teleopSpeakerNotePoints
   * @return teleopSpeakerNotePoints
   */
  @javax.annotation.Nullable

  public Integer getTeleopSpeakerNotePoints() {
    return teleopSpeakerNotePoints;
  }


  public void setTeleopSpeakerNotePoints(@javax.annotation.Nullable Integer teleopSpeakerNotePoints) {
    this.teleopSpeakerNotePoints = teleopSpeakerNotePoints;
  }

  public MatchScoreBreakdown2024Alliance teleopTotalNotePoints(@javax.annotation.Nullable Integer teleopTotalNotePoints) {
    
    this.teleopTotalNotePoints = teleopTotalNotePoints;
    return this;
  }

  /**
   * Get teleopTotalNotePoints
   * @return teleopTotalNotePoints
   */
  @javax.annotation.Nullable

  public Integer getTeleopTotalNotePoints() {
    return teleopTotalNotePoints;
  }


  public void setTeleopTotalNotePoints(@javax.annotation.Nullable Integer teleopTotalNotePoints) {
    this.teleopTotalNotePoints = teleopTotalNotePoints;
  }

  public MatchScoreBreakdown2024Alliance totalPoints(@javax.annotation.Nullable Integer totalPoints) {
    
    this.totalPoints = totalPoints;
    return this;
  }

  /**
   * Get totalPoints
   * @return totalPoints
   */
  @javax.annotation.Nullable

  public Integer getTotalPoints() {
    return totalPoints;
  }


  public void setTotalPoints(@javax.annotation.Nullable Integer totalPoints) {
    this.totalPoints = totalPoints;
  }

  public MatchScoreBreakdown2024Alliance trapCenterStage(@javax.annotation.Nullable Boolean trapCenterStage) {
    
    this.trapCenterStage = trapCenterStage;
    return this;
  }

  /**
   * Get trapCenterStage
   * @return trapCenterStage
   */
  @javax.annotation.Nullable

  public Boolean getTrapCenterStage() {
    return trapCenterStage;
  }


  public void setTrapCenterStage(@javax.annotation.Nullable Boolean trapCenterStage) {
    this.trapCenterStage = trapCenterStage;
  }

  public MatchScoreBreakdown2024Alliance trapStageLeft(@javax.annotation.Nullable Boolean trapStageLeft) {
    
    this.trapStageLeft = trapStageLeft;
    return this;
  }

  /**
   * Get trapStageLeft
   * @return trapStageLeft
   */
  @javax.annotation.Nullable

  public Boolean getTrapStageLeft() {
    return trapStageLeft;
  }


  public void setTrapStageLeft(@javax.annotation.Nullable Boolean trapStageLeft) {
    this.trapStageLeft = trapStageLeft;
  }

  public MatchScoreBreakdown2024Alliance trapStageRight(@javax.annotation.Nullable Boolean trapStageRight) {
    
    this.trapStageRight = trapStageRight;
    return this;
  }

  /**
   * Get trapStageRight
   * @return trapStageRight
   */
  @javax.annotation.Nullable

  public Boolean getTrapStageRight() {
    return trapStageRight;
  }


  public void setTrapStageRight(@javax.annotation.Nullable Boolean trapStageRight) {
    this.trapStageRight = trapStageRight;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchScoreBreakdown2024Alliance matchScoreBreakdown2024Alliance = (MatchScoreBreakdown2024Alliance) o;
    return Objects.equals(this.adjustPoints, matchScoreBreakdown2024Alliance.adjustPoints) &&
        Objects.equals(this.autoAmpNoteCount, matchScoreBreakdown2024Alliance.autoAmpNoteCount) &&
        Objects.equals(this.autoAmpNotePoints, matchScoreBreakdown2024Alliance.autoAmpNotePoints) &&
        Objects.equals(this.autoLeavePoints, matchScoreBreakdown2024Alliance.autoLeavePoints) &&
        Objects.equals(this.autoLineRobot1, matchScoreBreakdown2024Alliance.autoLineRobot1) &&
        Objects.equals(this.autoLineRobot2, matchScoreBreakdown2024Alliance.autoLineRobot2) &&
        Objects.equals(this.autoLineRobot3, matchScoreBreakdown2024Alliance.autoLineRobot3) &&
        Objects.equals(this.autoPoints, matchScoreBreakdown2024Alliance.autoPoints) &&
        Objects.equals(this.autoSpeakerNoteCount, matchScoreBreakdown2024Alliance.autoSpeakerNoteCount) &&
        Objects.equals(this.autoSpeakerNotePoints, matchScoreBreakdown2024Alliance.autoSpeakerNotePoints) &&
        Objects.equals(this.autoTotalNotePoints, matchScoreBreakdown2024Alliance.autoTotalNotePoints) &&
        Objects.equals(this.coopNotePlayed, matchScoreBreakdown2024Alliance.coopNotePlayed) &&
        Objects.equals(this.coopertitionBonusAchieved, matchScoreBreakdown2024Alliance.coopertitionBonusAchieved) &&
        Objects.equals(this.coopertitionCriteriaMet, matchScoreBreakdown2024Alliance.coopertitionCriteriaMet) &&
        Objects.equals(this.endGameHarmonyPoints, matchScoreBreakdown2024Alliance.endGameHarmonyPoints) &&
        Objects.equals(this.endGameNoteInTrapPoints, matchScoreBreakdown2024Alliance.endGameNoteInTrapPoints) &&
        Objects.equals(this.endGameOnStagePoints, matchScoreBreakdown2024Alliance.endGameOnStagePoints) &&
        Objects.equals(this.endGameParkPoints, matchScoreBreakdown2024Alliance.endGameParkPoints) &&
        Objects.equals(this.endGameRobot1, matchScoreBreakdown2024Alliance.endGameRobot1) &&
        Objects.equals(this.endGameRobot2, matchScoreBreakdown2024Alliance.endGameRobot2) &&
        Objects.equals(this.endGameRobot3, matchScoreBreakdown2024Alliance.endGameRobot3) &&
        Objects.equals(this.endGameSpotLightBonusPoints, matchScoreBreakdown2024Alliance.endGameSpotLightBonusPoints) &&
        Objects.equals(this.endGameTotalStagePoints, matchScoreBreakdown2024Alliance.endGameTotalStagePoints) &&
        Objects.equals(this.ensembleBonusAchieved, matchScoreBreakdown2024Alliance.ensembleBonusAchieved) &&
        Objects.equals(this.ensembleBonusOnStageRobotsThreshold, matchScoreBreakdown2024Alliance.ensembleBonusOnStageRobotsThreshold) &&
        Objects.equals(this.ensembleBonusStagePointsThreshold, matchScoreBreakdown2024Alliance.ensembleBonusStagePointsThreshold) &&
        Objects.equals(this.foulCount, matchScoreBreakdown2024Alliance.foulCount) &&
        Objects.equals(this.foulPoints, matchScoreBreakdown2024Alliance.foulPoints) &&
        Objects.equals(this.g206Penalty, matchScoreBreakdown2024Alliance.g206Penalty) &&
        Objects.equals(this.g408Penalty, matchScoreBreakdown2024Alliance.g408Penalty) &&
        Objects.equals(this.g424Penalty, matchScoreBreakdown2024Alliance.g424Penalty) &&
        Objects.equals(this.melodyBonusAchieved, matchScoreBreakdown2024Alliance.melodyBonusAchieved) &&
        Objects.equals(this.melodyBonusThreshold, matchScoreBreakdown2024Alliance.melodyBonusThreshold) &&
        Objects.equals(this.melodyBonusThresholdCoop, matchScoreBreakdown2024Alliance.melodyBonusThresholdCoop) &&
        Objects.equals(this.melodyBonusThresholdNonCoop, matchScoreBreakdown2024Alliance.melodyBonusThresholdNonCoop) &&
        Objects.equals(this.micCenterStage, matchScoreBreakdown2024Alliance.micCenterStage) &&
        Objects.equals(this.micStageLeft, matchScoreBreakdown2024Alliance.micStageLeft) &&
        Objects.equals(this.micStageRight, matchScoreBreakdown2024Alliance.micStageRight) &&
        Objects.equals(this.rp, matchScoreBreakdown2024Alliance.rp) &&
        Objects.equals(this.techFoulCount, matchScoreBreakdown2024Alliance.techFoulCount) &&
        Objects.equals(this.teleopAmpNoteCount, matchScoreBreakdown2024Alliance.teleopAmpNoteCount) &&
        Objects.equals(this.teleopAmpNotePoints, matchScoreBreakdown2024Alliance.teleopAmpNotePoints) &&
        Objects.equals(this.teleopPoints, matchScoreBreakdown2024Alliance.teleopPoints) &&
        Objects.equals(this.teleopSpeakerNoteAmplifiedCount, matchScoreBreakdown2024Alliance.teleopSpeakerNoteAmplifiedCount) &&
        Objects.equals(this.teleopSpeakerNoteAmplifiedPoints, matchScoreBreakdown2024Alliance.teleopSpeakerNoteAmplifiedPoints) &&
        Objects.equals(this.teleopSpeakerNoteCount, matchScoreBreakdown2024Alliance.teleopSpeakerNoteCount) &&
        Objects.equals(this.teleopSpeakerNotePoints, matchScoreBreakdown2024Alliance.teleopSpeakerNotePoints) &&
        Objects.equals(this.teleopTotalNotePoints, matchScoreBreakdown2024Alliance.teleopTotalNotePoints) &&
        Objects.equals(this.totalPoints, matchScoreBreakdown2024Alliance.totalPoints) &&
        Objects.equals(this.trapCenterStage, matchScoreBreakdown2024Alliance.trapCenterStage) &&
        Objects.equals(this.trapStageLeft, matchScoreBreakdown2024Alliance.trapStageLeft) &&
        Objects.equals(this.trapStageRight, matchScoreBreakdown2024Alliance.trapStageRight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adjustPoints, autoAmpNoteCount, autoAmpNotePoints, autoLeavePoints, autoLineRobot1, autoLineRobot2, autoLineRobot3, autoPoints, autoSpeakerNoteCount, autoSpeakerNotePoints, autoTotalNotePoints, coopNotePlayed, coopertitionBonusAchieved, coopertitionCriteriaMet, endGameHarmonyPoints, endGameNoteInTrapPoints, endGameOnStagePoints, endGameParkPoints, endGameRobot1, endGameRobot2, endGameRobot3, endGameSpotLightBonusPoints, endGameTotalStagePoints, ensembleBonusAchieved, ensembleBonusOnStageRobotsThreshold, ensembleBonusStagePointsThreshold, foulCount, foulPoints, g206Penalty, g408Penalty, g424Penalty, melodyBonusAchieved, melodyBonusThreshold, melodyBonusThresholdCoop, melodyBonusThresholdNonCoop, micCenterStage, micStageLeft, micStageRight, rp, techFoulCount, teleopAmpNoteCount, teleopAmpNotePoints, teleopPoints, teleopSpeakerNoteAmplifiedCount, teleopSpeakerNoteAmplifiedPoints, teleopSpeakerNoteCount, teleopSpeakerNotePoints, teleopTotalNotePoints, totalPoints, trapCenterStage, trapStageLeft, trapStageRight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchScoreBreakdown2024Alliance {\n");
    sb.append("    adjustPoints: ").append(toIndentedString(adjustPoints)).append("\n");
    sb.append("    autoAmpNoteCount: ").append(toIndentedString(autoAmpNoteCount)).append("\n");
    sb.append("    autoAmpNotePoints: ").append(toIndentedString(autoAmpNotePoints)).append("\n");
    sb.append("    autoLeavePoints: ").append(toIndentedString(autoLeavePoints)).append("\n");
    sb.append("    autoLineRobot1: ").append(toIndentedString(autoLineRobot1)).append("\n");
    sb.append("    autoLineRobot2: ").append(toIndentedString(autoLineRobot2)).append("\n");
    sb.append("    autoLineRobot3: ").append(toIndentedString(autoLineRobot3)).append("\n");
    sb.append("    autoPoints: ").append(toIndentedString(autoPoints)).append("\n");
    sb.append("    autoSpeakerNoteCount: ").append(toIndentedString(autoSpeakerNoteCount)).append("\n");
    sb.append("    autoSpeakerNotePoints: ").append(toIndentedString(autoSpeakerNotePoints)).append("\n");
    sb.append("    autoTotalNotePoints: ").append(toIndentedString(autoTotalNotePoints)).append("\n");
    sb.append("    coopNotePlayed: ").append(toIndentedString(coopNotePlayed)).append("\n");
    sb.append("    coopertitionBonusAchieved: ").append(toIndentedString(coopertitionBonusAchieved)).append("\n");
    sb.append("    coopertitionCriteriaMet: ").append(toIndentedString(coopertitionCriteriaMet)).append("\n");
    sb.append("    endGameHarmonyPoints: ").append(toIndentedString(endGameHarmonyPoints)).append("\n");
    sb.append("    endGameNoteInTrapPoints: ").append(toIndentedString(endGameNoteInTrapPoints)).append("\n");
    sb.append("    endGameOnStagePoints: ").append(toIndentedString(endGameOnStagePoints)).append("\n");
    sb.append("    endGameParkPoints: ").append(toIndentedString(endGameParkPoints)).append("\n");
    sb.append("    endGameRobot1: ").append(toIndentedString(endGameRobot1)).append("\n");
    sb.append("    endGameRobot2: ").append(toIndentedString(endGameRobot2)).append("\n");
    sb.append("    endGameRobot3: ").append(toIndentedString(endGameRobot3)).append("\n");
    sb.append("    endGameSpotLightBonusPoints: ").append(toIndentedString(endGameSpotLightBonusPoints)).append("\n");
    sb.append("    endGameTotalStagePoints: ").append(toIndentedString(endGameTotalStagePoints)).append("\n");
    sb.append("    ensembleBonusAchieved: ").append(toIndentedString(ensembleBonusAchieved)).append("\n");
    sb.append("    ensembleBonusOnStageRobotsThreshold: ").append(toIndentedString(ensembleBonusOnStageRobotsThreshold)).append("\n");
    sb.append("    ensembleBonusStagePointsThreshold: ").append(toIndentedString(ensembleBonusStagePointsThreshold)).append("\n");
    sb.append("    foulCount: ").append(toIndentedString(foulCount)).append("\n");
    sb.append("    foulPoints: ").append(toIndentedString(foulPoints)).append("\n");
    sb.append("    g206Penalty: ").append(toIndentedString(g206Penalty)).append("\n");
    sb.append("    g408Penalty: ").append(toIndentedString(g408Penalty)).append("\n");
    sb.append("    g424Penalty: ").append(toIndentedString(g424Penalty)).append("\n");
    sb.append("    melodyBonusAchieved: ").append(toIndentedString(melodyBonusAchieved)).append("\n");
    sb.append("    melodyBonusThreshold: ").append(toIndentedString(melodyBonusThreshold)).append("\n");
    sb.append("    melodyBonusThresholdCoop: ").append(toIndentedString(melodyBonusThresholdCoop)).append("\n");
    sb.append("    melodyBonusThresholdNonCoop: ").append(toIndentedString(melodyBonusThresholdNonCoop)).append("\n");
    sb.append("    micCenterStage: ").append(toIndentedString(micCenterStage)).append("\n");
    sb.append("    micStageLeft: ").append(toIndentedString(micStageLeft)).append("\n");
    sb.append("    micStageRight: ").append(toIndentedString(micStageRight)).append("\n");
    sb.append("    rp: ").append(toIndentedString(rp)).append("\n");
    sb.append("    techFoulCount: ").append(toIndentedString(techFoulCount)).append("\n");
    sb.append("    teleopAmpNoteCount: ").append(toIndentedString(teleopAmpNoteCount)).append("\n");
    sb.append("    teleopAmpNotePoints: ").append(toIndentedString(teleopAmpNotePoints)).append("\n");
    sb.append("    teleopPoints: ").append(toIndentedString(teleopPoints)).append("\n");
    sb.append("    teleopSpeakerNoteAmplifiedCount: ").append(toIndentedString(teleopSpeakerNoteAmplifiedCount)).append("\n");
    sb.append("    teleopSpeakerNoteAmplifiedPoints: ").append(toIndentedString(teleopSpeakerNoteAmplifiedPoints)).append("\n");
    sb.append("    teleopSpeakerNoteCount: ").append(toIndentedString(teleopSpeakerNoteCount)).append("\n");
    sb.append("    teleopSpeakerNotePoints: ").append(toIndentedString(teleopSpeakerNotePoints)).append("\n");
    sb.append("    teleopTotalNotePoints: ").append(toIndentedString(teleopTotalNotePoints)).append("\n");
    sb.append("    totalPoints: ").append(toIndentedString(totalPoints)).append("\n");
    sb.append("    trapCenterStage: ").append(toIndentedString(trapCenterStage)).append("\n");
    sb.append("    trapStageLeft: ").append(toIndentedString(trapStageLeft)).append("\n");
    sb.append("    trapStageRight: ").append(toIndentedString(trapStageRight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

