/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import thebluealliance.api.model.MatchScoreBreakdown2025AllianceAutoReefTopRow;

/**
 * MatchScoreBreakdown2025AllianceAutoReef
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class MatchScoreBreakdown2025AllianceAutoReef {
  public static final String SERIALIZED_NAME_TOP_ROW = "topRow";
  @SerializedName(SERIALIZED_NAME_TOP_ROW)
  @javax.annotation.Nonnull
  private MatchScoreBreakdown2025AllianceAutoReefTopRow topRow;

  public static final String SERIALIZED_NAME_MID_ROW = "midRow";
  @SerializedName(SERIALIZED_NAME_MID_ROW)
  @javax.annotation.Nonnull
  private MatchScoreBreakdown2025AllianceAutoReefTopRow midRow;

  public static final String SERIALIZED_NAME_BOT_ROW = "botRow";
  @SerializedName(SERIALIZED_NAME_BOT_ROW)
  @javax.annotation.Nonnull
  private MatchScoreBreakdown2025AllianceAutoReefTopRow botRow;

  public static final String SERIALIZED_NAME_TROUGH = "trough";
  @SerializedName(SERIALIZED_NAME_TROUGH)
  @javax.annotation.Nonnull
  private Integer trough;

  public static final String SERIALIZED_NAME_TBA_BOT_ROW_COUNT = "tba_botRowCount";
  @SerializedName(SERIALIZED_NAME_TBA_BOT_ROW_COUNT)
  @javax.annotation.Nullable
  private Integer tbaBotRowCount;

  public static final String SERIALIZED_NAME_TBA_MID_ROW_COUNT = "tba_midRowCount";
  @SerializedName(SERIALIZED_NAME_TBA_MID_ROW_COUNT)
  @javax.annotation.Nullable
  private Integer tbaMidRowCount;

  public static final String SERIALIZED_NAME_TBA_TOP_ROW_COUNT = "tba_topRowCount";
  @SerializedName(SERIALIZED_NAME_TBA_TOP_ROW_COUNT)
  @javax.annotation.Nullable
  private Integer tbaTopRowCount;

  public MatchScoreBreakdown2025AllianceAutoReef() {
  }

  public MatchScoreBreakdown2025AllianceAutoReef topRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow topRow) {
    
    this.topRow = topRow;
    return this;
  }

  /**
   * Get topRow
   * @return topRow
   */
  @javax.annotation.Nonnull

  public MatchScoreBreakdown2025AllianceAutoReefTopRow getTopRow() {
    return topRow;
  }


  public void setTopRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow topRow) {
    this.topRow = topRow;
  }

  public MatchScoreBreakdown2025AllianceAutoReef midRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow midRow) {
    
    this.midRow = midRow;
    return this;
  }

  /**
   * Get midRow
   * @return midRow
   */
  @javax.annotation.Nonnull

  public MatchScoreBreakdown2025AllianceAutoReefTopRow getMidRow() {
    return midRow;
  }


  public void setMidRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow midRow) {
    this.midRow = midRow;
  }

  public MatchScoreBreakdown2025AllianceAutoReef botRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow botRow) {
    
    this.botRow = botRow;
    return this;
  }

  /**
   * Get botRow
   * @return botRow
   */
  @javax.annotation.Nonnull

  public MatchScoreBreakdown2025AllianceAutoReefTopRow getBotRow() {
    return botRow;
  }


  public void setBotRow(@javax.annotation.Nonnull MatchScoreBreakdown2025AllianceAutoReefTopRow botRow) {
    this.botRow = botRow;
  }

  public MatchScoreBreakdown2025AllianceAutoReef trough(@javax.annotation.Nonnull Integer trough) {
    
    this.trough = trough;
    return this;
  }

  /**
   * Get trough
   * @return trough
   */
  @javax.annotation.Nonnull

  public Integer getTrough() {
    return trough;
  }


  public void setTrough(@javax.annotation.Nonnull Integer trough) {
    this.trough = trough;
  }

  public MatchScoreBreakdown2025AllianceAutoReef tbaBotRowCount(@javax.annotation.Nullable Integer tbaBotRowCount) {
    
    this.tbaBotRowCount = tbaBotRowCount;
    return this;
  }

  /**
   * Unofficial TBA-computed value that sums the total number of game pieces scored in the botRow object.
   * @return tbaBotRowCount
   */
  @javax.annotation.Nullable

  public Integer getTbaBotRowCount() {
    return tbaBotRowCount;
  }


  public void setTbaBotRowCount(@javax.annotation.Nullable Integer tbaBotRowCount) {
    this.tbaBotRowCount = tbaBotRowCount;
  }

  public MatchScoreBreakdown2025AllianceAutoReef tbaMidRowCount(@javax.annotation.Nullable Integer tbaMidRowCount) {
    
    this.tbaMidRowCount = tbaMidRowCount;
    return this;
  }

  /**
   * Unofficial TBA-computed value that sums the total number of game pieces scored in the midRow object.
   * @return tbaMidRowCount
   */
  @javax.annotation.Nullable

  public Integer getTbaMidRowCount() {
    return tbaMidRowCount;
  }


  public void setTbaMidRowCount(@javax.annotation.Nullable Integer tbaMidRowCount) {
    this.tbaMidRowCount = tbaMidRowCount;
  }

  public MatchScoreBreakdown2025AllianceAutoReef tbaTopRowCount(@javax.annotation.Nullable Integer tbaTopRowCount) {
    
    this.tbaTopRowCount = tbaTopRowCount;
    return this;
  }

  /**
   * Unofficial TBA-computed value that sums the total number of game pieces scored in the topRow object.
   * @return tbaTopRowCount
   */
  @javax.annotation.Nullable

  public Integer getTbaTopRowCount() {
    return tbaTopRowCount;
  }


  public void setTbaTopRowCount(@javax.annotation.Nullable Integer tbaTopRowCount) {
    this.tbaTopRowCount = tbaTopRowCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchScoreBreakdown2025AllianceAutoReef matchScoreBreakdown2025AllianceAutoReef = (MatchScoreBreakdown2025AllianceAutoReef) o;
    return Objects.equals(this.topRow, matchScoreBreakdown2025AllianceAutoReef.topRow) &&
        Objects.equals(this.midRow, matchScoreBreakdown2025AllianceAutoReef.midRow) &&
        Objects.equals(this.botRow, matchScoreBreakdown2025AllianceAutoReef.botRow) &&
        Objects.equals(this.trough, matchScoreBreakdown2025AllianceAutoReef.trough) &&
        Objects.equals(this.tbaBotRowCount, matchScoreBreakdown2025AllianceAutoReef.tbaBotRowCount) &&
        Objects.equals(this.tbaMidRowCount, matchScoreBreakdown2025AllianceAutoReef.tbaMidRowCount) &&
        Objects.equals(this.tbaTopRowCount, matchScoreBreakdown2025AllianceAutoReef.tbaTopRowCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topRow, midRow, botRow, trough, tbaBotRowCount, tbaMidRowCount, tbaTopRowCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchScoreBreakdown2025AllianceAutoReef {\n");
    sb.append("    topRow: ").append(toIndentedString(topRow)).append("\n");
    sb.append("    midRow: ").append(toIndentedString(midRow)).append("\n");
    sb.append("    botRow: ").append(toIndentedString(botRow)).append("\n");
    sb.append("    trough: ").append(toIndentedString(trough)).append("\n");
    sb.append("    tbaBotRowCount: ").append(toIndentedString(tbaBotRowCount)).append("\n");
    sb.append("    tbaMidRowCount: ").append(toIndentedString(tbaMidRowCount)).append("\n");
    sb.append("    tbaTopRowCount: ").append(toIndentedString(tbaTopRowCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

