/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import thebluealliance.api.model.SearchIndexEventsInner;
import thebluealliance.api.model.SearchIndexTeamsInner;

/**
 * SearchIndex
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class SearchIndex {
  public static final String SERIALIZED_NAME_TEAMS = "teams";
  @SerializedName(SERIALIZED_NAME_TEAMS)
  @javax.annotation.Nonnull
  private List<SearchIndexTeamsInner> teams = new ArrayList<>();

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  @javax.annotation.Nonnull
  private List<SearchIndexEventsInner> events = new ArrayList<>();

  public SearchIndex() {
  }

  public SearchIndex teams(@javax.annotation.Nonnull List<SearchIndexTeamsInner> teams) {
    
    this.teams = teams;
    return this;
  }

  public SearchIndex addTeamsItem(SearchIndexTeamsInner teamsItem) {
    if (this.teams == null) {
      this.teams = new ArrayList<>();
    }
    this.teams.add(teamsItem);
    return this;
  }

  /**
   * Get teams
   * @return teams
   */
  @javax.annotation.Nonnull

  public List<SearchIndexTeamsInner> getTeams() {
    return teams;
  }


  public void setTeams(@javax.annotation.Nonnull List<SearchIndexTeamsInner> teams) {
    this.teams = teams;
  }

  public SearchIndex events(@javax.annotation.Nonnull List<SearchIndexEventsInner> events) {
    
    this.events = events;
    return this;
  }

  public SearchIndex addEventsItem(SearchIndexEventsInner eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @javax.annotation.Nonnull

  public List<SearchIndexEventsInner> getEvents() {
    return events;
  }


  public void setEvents(@javax.annotation.Nonnull List<SearchIndexEventsInner> events) {
    this.events = events;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchIndex searchIndex = (SearchIndex) o;
    return Objects.equals(this.teams, searchIndex.teams) &&
        Objects.equals(this.events, searchIndex.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teams, events);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchIndex {\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

