/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import thebluealliance.api.model.WLTRecord;

/**
 * TeamEventStatusRankRanking
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class TeamEventStatusRankRanking {
  public static final String SERIALIZED_NAME_MATCHES_PLAYED = "matches_played";
  @SerializedName(SERIALIZED_NAME_MATCHES_PLAYED)
  @javax.annotation.Nullable
  private Integer matchesPlayed;

  public static final String SERIALIZED_NAME_QUAL_AVERAGE = "qual_average";
  @SerializedName(SERIALIZED_NAME_QUAL_AVERAGE)
  @javax.annotation.Nullable
  private Double qualAverage;

  public static final String SERIALIZED_NAME_SORT_ORDERS = "sort_orders";
  @SerializedName(SERIALIZED_NAME_SORT_ORDERS)
  @javax.annotation.Nullable
  private List<Double> sortOrders = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECORD = "record";
  @SerializedName(SERIALIZED_NAME_RECORD)
  @javax.annotation.Nullable
  private WLTRecord record;

  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  @javax.annotation.Nullable
  private Integer rank;

  public static final String SERIALIZED_NAME_DQ = "dq";
  @SerializedName(SERIALIZED_NAME_DQ)
  @javax.annotation.Nullable
  private Integer dq;

  public static final String SERIALIZED_NAME_TEAM_KEY = "team_key";
  @SerializedName(SERIALIZED_NAME_TEAM_KEY)
  @javax.annotation.Nullable
  private String teamKey;

  public TeamEventStatusRankRanking() {
  }

  public TeamEventStatusRankRanking matchesPlayed(@javax.annotation.Nullable Integer matchesPlayed) {
    
    this.matchesPlayed = matchesPlayed;
    return this;
  }

  /**
   * Number of matches played.
   * @return matchesPlayed
   */
  @javax.annotation.Nullable

  public Integer getMatchesPlayed() {
    return matchesPlayed;
  }


  public void setMatchesPlayed(@javax.annotation.Nullable Integer matchesPlayed) {
    this.matchesPlayed = matchesPlayed;
  }

  public TeamEventStatusRankRanking qualAverage(@javax.annotation.Nullable Double qualAverage) {
    
    this.qualAverage = qualAverage;
    return this;
  }

  /**
   * For some years, average qualification score. Can be null.
   * @return qualAverage
   */
  @javax.annotation.Nullable

  public Double getQualAverage() {
    return qualAverage;
  }


  public void setQualAverage(@javax.annotation.Nullable Double qualAverage) {
    this.qualAverage = qualAverage;
  }

  public TeamEventStatusRankRanking sortOrders(@javax.annotation.Nullable List<Double> sortOrders) {
    
    this.sortOrders = sortOrders;
    return this;
  }

  public TeamEventStatusRankRanking addSortOrdersItem(Double sortOrdersItem) {
    if (this.sortOrders == null) {
      this.sortOrders = new ArrayList<>();
    }
    this.sortOrders.add(sortOrdersItem);
    return this;
  }

  /**
   * Ordered list of values used to determine the rank. See the &#x60;sort_order_info&#x60; property for the name of each value.
   * @return sortOrders
   */
  @javax.annotation.Nullable

  public List<Double> getSortOrders() {
    return sortOrders;
  }


  public void setSortOrders(@javax.annotation.Nullable List<Double> sortOrders) {
    this.sortOrders = sortOrders;
  }

  public TeamEventStatusRankRanking record(@javax.annotation.Nullable WLTRecord record) {
    
    this.record = record;
    return this;
  }

  /**
   * Get record
   * @return record
   */
  @javax.annotation.Nullable

  public WLTRecord getRecord() {
    return record;
  }


  public void setRecord(@javax.annotation.Nullable WLTRecord record) {
    this.record = record;
  }

  public TeamEventStatusRankRanking rank(@javax.annotation.Nullable Integer rank) {
    
    this.rank = rank;
    return this;
  }

  /**
   * Relative rank of this team.
   * @return rank
   */
  @javax.annotation.Nullable

  public Integer getRank() {
    return rank;
  }


  public void setRank(@javax.annotation.Nullable Integer rank) {
    this.rank = rank;
  }

  public TeamEventStatusRankRanking dq(@javax.annotation.Nullable Integer dq) {
    
    this.dq = dq;
    return this;
  }

  /**
   * Number of matches the team was disqualified for.
   * @return dq
   */
  @javax.annotation.Nullable

  public Integer getDq() {
    return dq;
  }


  public void setDq(@javax.annotation.Nullable Integer dq) {
    this.dq = dq;
  }

  public TeamEventStatusRankRanking teamKey(@javax.annotation.Nullable String teamKey) {
    
    this.teamKey = teamKey;
    return this;
  }

  /**
   * TBA team key for this rank.
   * @return teamKey
   */
  @javax.annotation.Nullable

  public String getTeamKey() {
    return teamKey;
  }


  public void setTeamKey(@javax.annotation.Nullable String teamKey) {
    this.teamKey = teamKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamEventStatusRankRanking teamEventStatusRankRanking = (TeamEventStatusRankRanking) o;
    return Objects.equals(this.matchesPlayed, teamEventStatusRankRanking.matchesPlayed) &&
        Objects.equals(this.qualAverage, teamEventStatusRankRanking.qualAverage) &&
        Objects.equals(this.sortOrders, teamEventStatusRankRanking.sortOrders) &&
        Objects.equals(this.record, teamEventStatusRankRanking.record) &&
        Objects.equals(this.rank, teamEventStatusRankRanking.rank) &&
        Objects.equals(this.dq, teamEventStatusRankRanking.dq) &&
        Objects.equals(this.teamKey, teamEventStatusRankRanking.teamKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchesPlayed, qualAverage, sortOrders, record, rank, dq, teamKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamEventStatusRankRanking {\n");
    sb.append("    matchesPlayed: ").append(toIndentedString(matchesPlayed)).append("\n");
    sb.append("    qualAverage: ").append(toIndentedString(qualAverage)).append("\n");
    sb.append("    sortOrders: ").append(toIndentedString(sortOrders)).append("\n");
    sb.append("    record: ").append(toIndentedString(record)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    dq: ").append(toIndentedString(dq)).append("\n");
    sb.append("    teamKey: ").append(toIndentedString(teamKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

