/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package thebluealliance.api.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * TeamEventStatusAlliance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-19T09:18:44.421555100-05:00[America/Chicago]", comments = "Generator version: 7.13.0")
public class TeamEventStatusAlliance {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  @javax.annotation.Nonnull
  private Integer number;

  public static final String SERIALIZED_NAME_BACKUP = "backup";
  @SerializedName(SERIALIZED_NAME_BACKUP)
  @javax.annotation.Nullable
  private TeamEventStatusAllianceBackup backup = null;

  public static final String SERIALIZED_NAME_PICK = "pick";
  @SerializedName(SERIALIZED_NAME_PICK)
  @javax.annotation.Nonnull
  private Integer pick;

  public TeamEventStatusAlliance() {
  }

  public TeamEventStatusAlliance name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Alliance name, may be null.
   * @return name
   */
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public TeamEventStatusAlliance number(@javax.annotation.Nonnull Integer number) {
    
    this.number = number;
    return this;
  }

  /**
   * Alliance number.
   * @return number
   */
  @javax.annotation.Nonnull

  public Integer getNumber() {
    return number;
  }


  public void setNumber(@javax.annotation.Nonnull Integer number) {
    this.number = number;
  }

  public TeamEventStatusAlliance backup(@javax.annotation.Nullable TeamEventStatusAllianceBackup backup) {
    
    this.backup = backup;
    return this;
  }

  /**
   * Backup status, may be null.
   * @return backup
   */
  @javax.annotation.Nullable

  public TeamEventStatusAllianceBackup getBackup() {
    return backup;
  }


  public void setBackup(@javax.annotation.Nullable TeamEventStatusAllianceBackup backup) {
    this.backup = backup;
  }

  public TeamEventStatusAlliance pick(@javax.annotation.Nonnull Integer pick) {
    
    this.pick = pick;
    return this;
  }

  /**
   * Order the team was picked in the alliance from 0-2, with 0 being alliance captain.
   * @return pick
   */
  @javax.annotation.Nonnull

  public Integer getPick() {
    return pick;
  }


  public void setPick(@javax.annotation.Nonnull Integer pick) {
    this.pick = pick;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamEventStatusAlliance teamEventStatusAlliance = (TeamEventStatusAlliance) o;
    return Objects.equals(this.name, teamEventStatusAlliance.name) &&
        Objects.equals(this.number, teamEventStatusAlliance.number) &&
        Objects.equals(this.backup, teamEventStatusAlliance.backup) &&
        Objects.equals(this.pick, teamEventStatusAlliance.pick);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, number, backup, pick);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamEventStatusAlliance {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    backup: ").append(toIndentedString(backup)).append("\n");
    sb.append("    pick: ").append(toIndentedString(pick)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

