/**
 * The Blue Alliance API
 * Access data about the FIRST Robotics Competition
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.thebluealliance.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.annotation.Nullable;


/**
 * Event
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-27T14:59:25.379-04:00")
public class Event   {
  @SerializedName("alliances")
  private String alliances = null;

  @SerializedName("competitionWeek")
  private Integer competitionWeek = null;

  @SerializedName("endDate")
  private Long endDate = null;

  @SerializedName("event_code")
  private String eventCode = null;

  @SerializedName("event_district")
  private Integer eventDistrict = null;

  @SerializedName("event_district_string")
  private String eventDistrictString = null;

  @SerializedName("event_type")
  private Integer eventType = null;

  @SerializedName("event_type_string")
  private String eventTypeString = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("lastModified")
  private Long lastModified = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("official")
  private Boolean official = null;

  @SerializedName("short_name")
  private String shortName = null;

  @SerializedName("startDate")
  private Long startDate = null;

  @SerializedName("timezone")
  private String timezone = null;

  @SerializedName("venue_address")
  private String venueAddress = null;

  @SerializedName("webcasts")
  private String webcasts = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("year")
  private Integer year = null;

  public Event alliances(String alliances) {
    this.alliances = alliances;
    return this;
  }

   /**
   * If we have alliance selection data for this event, this contains a JSON array of the alliances. The captain is the first team, followed by their picks, in order.
   * @return alliances
  **/
  @ApiModelProperty(example = "null", value = "If we have alliance selection data for this event, this contains a JSON array of the alliances. The captain is the first team, followed by their picks, in order.")
  @Nullable
  public String getAlliances() {
    return alliances;
  }

  public void setAlliances(String alliances) {
    this.alliances = alliances;
  }

  public Event competitionWeek(Integer competitionWeek) {
    this.competitionWeek = competitionWeek;
    return this;
  }

   /**
   * Week of the season the event occurs on
   * @return competitionWeek
  **/
  @ApiModelProperty(example = "null", value = "Week of the season the event occurs on")
  @Nullable
  public Integer getCompetitionWeek() {
    return competitionWeek;
  }

  public void setCompetitionWeek(Integer competitionWeek) {
    this.competitionWeek = competitionWeek;
  }

  public Event endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * When the event ends
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "When the event ends")
  @Nullable
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public Event eventCode(String eventCode) {
    this.eventCode = eventCode;
    return this;
  }

   /**
   * Event short code, as provided by FIRST
   * @return eventCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "Event short code, as provided by FIRST")
  
  public String getEventCode() {
    return eventCode;
  }

  public void setEventCode(String eventCode) {
    this.eventCode = eventCode;
  }

  public Event eventDistrict(Integer eventDistrict) {
    this.eventDistrict = eventDistrict;
    return this;
  }

   /**
   * An integer that represents the event district as a constant.
   * @return eventDistrict
  **/
  @ApiModelProperty(example = "null", value = "An integer that represents the event district as a constant.")
  @Nullable
  public Integer getEventDistrict() {
    return eventDistrict;
  }

  public void setEventDistrict(Integer eventDistrict) {
    this.eventDistrict = eventDistrict;
  }

  public Event eventDistrictString(String eventDistrictString) {
    this.eventDistrictString = eventDistrictString;
    return this;
  }

   /**
   * A human readable string that defines the event's district.
   * @return eventDistrictString
  **/
  @ApiModelProperty(example = "null", value = "A human readable string that defines the event's district.")
  @Nullable
  public String getEventDistrictString() {
    return eventDistrictString;
  }

  public void setEventDistrictString(String eventDistrictString) {
    this.eventDistrictString = eventDistrictString;
  }

  public Event eventType(Integer eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * An integer that represents the event type as a constant.
   * @return eventType
  **/
  @ApiModelProperty(example = "null", value = "An integer that represents the event type as a constant.")
  @Nullable
  public Integer getEventType() {
    return eventType;
  }

  public void setEventType(Integer eventType) {
    this.eventType = eventType;
  }

  public Event eventTypeString(String eventTypeString) {
    this.eventTypeString = eventTypeString;
    return this;
  }

   /**
   * A human readable string that defines the event type.
   * @return eventTypeString
  **/
  @ApiModelProperty(example = "null", value = "A human readable string that defines the event type.")
  @Nullable
  public String getEventTypeString() {
    return eventTypeString;
  }

  public void setEventTypeString(String eventTypeString) {
    this.eventTypeString = eventTypeString;
  }

  public Event key(String key) {
    this.key = key;
    return this;
  }

   /**
   * TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.
   * @return key
  **/
  @ApiModelProperty(example = "null", required = true, value = "TBA event key with the format yyyy[EVENT_CODE], where yyyy is the year, and EVENT_CODE is the event code of the event.")
  
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Event lastModified(Long lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Timestamp this model was last modified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "Timestamp this model was last modified")
  @Nullable
  public Long getLastModified() {
    return lastModified;
  }

  public void setLastModified(Long lastModified) {
    this.lastModified = lastModified;
  }

  public Event location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Long form address that includes city, and state provided by FIRST
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "Long form address that includes city, and state provided by FIRST")
  @Nullable
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public Event name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Official name of event on record either provided by FIRST or organizers of offseason event.
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "Official name of event on record either provided by FIRST or organizers of offseason event.")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Event official(Boolean official) {
    this.official = official;
    return this;
  }

   /**
   * Whether this is a FIRST official event, or an offseaon event.
   * @return official
  **/
  @ApiModelProperty(example = "null", value = "Whether this is a FIRST official event, or an offseaon event.")
  @Nullable
  public Boolean getOfficial() {
    return official;
  }

  public void setOfficial(Boolean official) {
    this.official = official;
  }

  public Event shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Same as name but doesn't include event specifiers, such as 'Regional' or 'District'. May be null.
   * @return shortName
  **/
  @ApiModelProperty(example = "null", value = "Same as name but doesn't include event specifiers, such as 'Regional' or 'District'. May be null.")
  @Nullable
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public Event startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * When the event starts
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "When the event starts")
  @Nullable
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public Event timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone name
   * @return timezone
  **/
  @ApiModelProperty(example = "null", value = "Timezone name")
  @Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public Event venueAddress(String venueAddress) {
    this.venueAddress = venueAddress;
    return this;
  }

   /**
   * Address of the event's venue, if available. Line breaks included.
   * @return venueAddress
  **/
  @ApiModelProperty(example = "null", value = "Address of the event's venue, if available. Line breaks included.")
  @Nullable
  public String getVenueAddress() {
    return venueAddress;
  }

  public void setVenueAddress(String venueAddress) {
    this.venueAddress = venueAddress;
  }

  public Event webcasts(String webcasts) {
    this.webcasts = webcasts;
    return this;
  }

   /**
   * If the event has webcast data associated with it, this contains JSON data of the streams
   * @return webcasts
  **/
  @ApiModelProperty(example = "null", value = "If the event has webcast data associated with it, this contains JSON data of the streams")
  @Nullable
  public String getWebcasts() {
    return webcasts;
  }

  public void setWebcasts(String webcasts) {
    this.webcasts = webcasts;
  }

  public Event website(String website) {
    this.website = website;
    return this;
  }

   /**
   * The event's website, if any.
   * @return website
  **/
  @ApiModelProperty(example = "null", value = "The event's website, if any.")
  @Nullable
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Event year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Year the event data is for.
   * @return year
  **/
  @ApiModelProperty(example = "null", required = true, value = "Year the event data is for.")
  
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.alliances, event.alliances) &&
        Objects.equals(this.competitionWeek, event.competitionWeek) &&
        Objects.equals(this.endDate, event.endDate) &&
        Objects.equals(this.eventCode, event.eventCode) &&
        Objects.equals(this.eventDistrict, event.eventDistrict) &&
        Objects.equals(this.eventDistrictString, event.eventDistrictString) &&
        Objects.equals(this.eventType, event.eventType) &&
        Objects.equals(this.eventTypeString, event.eventTypeString) &&
        Objects.equals(this.key, event.key) &&
        Objects.equals(this.lastModified, event.lastModified) &&
        Objects.equals(this.location, event.location) &&
        Objects.equals(this.name, event.name) &&
        Objects.equals(this.official, event.official) &&
        Objects.equals(this.shortName, event.shortName) &&
        Objects.equals(this.startDate, event.startDate) &&
        Objects.equals(this.timezone, event.timezone) &&
        Objects.equals(this.venueAddress, event.venueAddress) &&
        Objects.equals(this.webcasts, event.webcasts) &&
        Objects.equals(this.website, event.website) &&
        Objects.equals(this.year, event.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alliances, competitionWeek, endDate, eventCode, eventDistrict, eventDistrictString, eventType, eventTypeString, key, lastModified, location, name, official, shortName, startDate, timezone, venueAddress, webcasts, website, year);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    
    sb.append("    alliances: ").append(toIndentedString(alliances)).append("\n");
    sb.append("    competitionWeek: ").append(toIndentedString(competitionWeek)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    eventCode: ").append(toIndentedString(eventCode)).append("\n");
    sb.append("    eventDistrict: ").append(toIndentedString(eventDistrict)).append("\n");
    sb.append("    eventDistrictString: ").append(toIndentedString(eventDistrictString)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    eventTypeString: ").append(toIndentedString(eventTypeString)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    official: ").append(toIndentedString(official)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    venueAddress: ").append(toIndentedString(venueAddress)).append("\n");
    sb.append("    webcasts: ").append(toIndentedString(webcasts)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

