/**
 * The Blue Alliance APIv3
 * Access data about the FIRST Robotics Competition
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.thebluealliance.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.annotation.Nullable;


/**
 * Media
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-16T16:55:35.065-05:00")
public interface IMedia   {


   /**
   * If the media requires it, a json dict of additional information
   * @return details
  **/
  @ApiModelProperty(example = "null", value = "If the media requires it, a json dict of additional information")
  @Nullable
  public String getDetails();

  public void setDetails(String details);



   /**
   * The key used to indentify this media element on the remote site (e.g YouTube video key)
   * @return foreignKey
  **/
  @ApiModelProperty(example = "null", required = true, value = "The key used to indentify this media element on the remote site (e.g YouTube video key)")
  
  public String getForeignKey();

  public void setForeignKey(String foreignKey);



   /**
   * Timestamp this model was last modified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "Timestamp this model was last modified")
  @Nullable
  public Long getLastModified();

  public void setLastModified(Long lastModified);



   /**
   * Is this a high quality robot picture
   * @return preferred
  **/
  @ApiModelProperty(example = "null", required = true, value = "Is this a high quality robot picture")
  
  public Boolean getPreferred();

  public void setPreferred(Boolean preferred);



   /**
   * The string type of the media element
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "The string type of the media element")
  
  public String getType();

  public void setType(String type);

}

