/**
 * The Blue Alliance APIv3
 * Access data about the FIRST Robotics Competition
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.thebluealliance.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;


/**
 * RankingItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-18T12:56:17.757-05:00")
public interface IRankingItem   {


   /**
   * Number of times the team was disqualified from a match
   * @return dq
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of times the team was disqualified from a match")
  
  public Integer getDq();

  public void setDq(Integer dq);



   /**
   * Timestamp this model was last modified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "Timestamp this model was last modified")
  @Nullable
  public Long getLastModified();

  public void setLastModified(Long lastModified);



   /**
   * Number of losses
   * @return losses
  **/
  @ApiModelProperty(example = "null", value = "Number of losses")
  @Nullable
  public Integer getLosses();

  public void setLosses(Integer losses);



   /**
   * Number of matches this team has played
   * @return matchesPlayed
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of matches this team has played")
  
  public Integer getMatchesPlayed();

  public void setMatchesPlayed(Integer matchesPlayed);



   /**
   * For some years, average qualification score
   * @return qualAverage
  **/
  @ApiModelProperty(example = "null", value = "For some years, average qualification score")
  @Nullable
  public Double getQualAverage();

  public void setQualAverage(Double qualAverage);



   /**
   * Ranking of this team
   * @return rank
  **/
  @ApiModelProperty(example = "null", required = true, value = "Ranking of this team")
  
  public Integer getRank();

  public void setRank(Integer rank);





   /**
   * Year-specific ranking values
   * @return sortOrders
  **/
  @ApiModelProperty(example = "null", required = true, value = "Year-specific ranking values")
  
  public List<Double> getSortOrders();

  public void setSortOrders(List<Double> sortOrders);



   /**
   * ITeam this item is for
   * @return teamKey
  **/
  @ApiModelProperty(example = "null", required = true, value = "Team this item is for")
  
  public String getTeamKey();

  public void setTeamKey(String teamKey);



   /**
   * Number of ties
   * @return ties
  **/
  @ApiModelProperty(example = "null", value = "Number of ties")
  @Nullable
  public Integer getTies();

  public void setTies(Integer ties);



   /**
   * Number of wins
   * @return wins
  **/
  @ApiModelProperty(example = "null", value = "Number of wins")
  @Nullable
  public Integer getWins();

  public void setWins(Integer wins);

}

