/**
 * The Blue Alliance APIv3
 * Access data about the FIRST Robotics Competition
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.thebluealliance.api.model;

import java.util.List;

import javax.annotation.Nullable;

import io.swagger.annotations.ApiModelProperty;


/**
 * RankingItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-16T16:55:35.065-05:00")
public interface IRankingItem   {


   /**
   * Number of times the team was disqualified from a match
   * @return dq
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of times the team was disqualified from a match")
  
  public Integer getDq();

  public void setDq(Integer dq);



   /**
   * Timestamp this model was last modified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "Timestamp this model was last modified")
  @Nullable
  public Long getLastModified();

  public void setLastModified(Long lastModified);



   /**
   * Number of matches this team has played
   * @return matchesPlayed
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of matches this team has played")
  
  public Integer getMatchesPlayed();

  public void setMatchesPlayed(Integer matchesPlayed);



   /**
   * For some years, average qualification score
   * @return qualAverage
  **/
  @ApiModelProperty(example = "null", value = "For some years, average qualification score")
  @Nullable
  public Integer getQualAverage();

  public void setQualAverage(Integer qualAverage);



   /**
   * Ranking of this team
   * @return rank
  **/
  @ApiModelProperty(example = "null", required = true, value = "Ranking of this team")
  
  public Integer getRank();

  public void setRank(Integer rank);



   /**
   * Get record
   * @return record
  **/
  @ApiModelProperty(example = "null", value = "")
  @Nullable
  public IRankingItemRecord getRecord();

  public void setRecord(IRankingItemRecord record);





   /**
   * Year-specific ranking values
   * @return sortOrders
  **/
  @ApiModelProperty(example = "null", required = true, value = "Year-specific ranking values")
  
  public List<Double> getSortOrders();

  public void setSortOrders(List<Double> sortOrders);



   /**
   * Team this item is for
   * @return teamKey
  **/
  @ApiModelProperty(example = "null", required = true, value = "Team this item is for")
  
  public String getTeamKey();

  public void setTeamKey(String teamKey);

}

