/**
 * The Blue Alliance APIv3
 * Access data about the FIRST Robotics Competition
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.thebluealliance.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.annotation.Nullable;


/**
 * TeamRecord
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-30T15:18:38.021-04:00")
public interface ITeamRecord   {


   /**
   * Number of losses
   * @return losses
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of losses")
  
  public Integer getLosses();

  public void setLosses(Integer losses);



   /**
   * Number of ties
   * @return ties
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of ties")
  
  public Integer getTies();

  public void setTies(Integer ties);



   /**
   * Number of wins
   * @return wins
  **/
  @ApiModelProperty(example = "null", required = true, value = "Number of wins")
  
  public Integer getWins();

  public void setWins(Integer wins);

}

